### ISSUE TITLE
enroot import failing with NFS and Lustre directories (could not create destination file)

### ISSUE THREAD

**Issue by zPianodude** [NVIDIA/enroot#10]
Image import failing on file output with permission error for certain NFS and Lustre filesystems.  Have tried changing mksquashfs options (-force-uid, etc.) with no solution.  

**Failing import** 
(note /mnt/scratch/lcapps has permissions 777)

lcapps@xxx:/mnt/scratch/lcapps/$ enroot import --output nccl.squash 'docker://ubuntu'
[INFO] Querying registry for permission grant
[INFO] Authenticating with user: <anonymous>
[INFO] Authentication succeeded
[INFO] Fetching image manifest
[INFO] Found all digests in cache
[INFO] Extracting image layers...

100% 4:0=0s 5b7339215d1d5f8e68622d584a224f60339f5bef41dbd74330d081e912f0cddd                                                                                                           

[INFO] Converting whiteouts...

100% 4:0=0s 5b7339215d1d5f8e68622d584a224f60339f5bef41dbd74330d081e912f0cddd                                                                                                           

[INFO] Creating squashfs filesystem...

_Could not create destination file: No such file or directory_

-----------------------------------------------------------------
**Passing import:**

lcapps@xxx:/mnt/scratch/lcapps$ enroot import --output /tmp/nccl.squash 'docker://ubuntu'
[INFO] Querying registry for permission grant
[INFO] Found valid credentials in cache
[INFO] Fetching image manifest
[INFO] Found all digests in cache
[INFO] Extracting image layers...

100% 4:0=0s 5b7339215d1d5f8e68622d584a224f60339f5bef41dbd74330d081e912f0cddd                                                                                                           

[INFO] Converting whiteouts...

100% 4:0=0s 5b7339215d1d5f8e68622d584a224f60339f5bef41dbd74330d081e912f0cddd                                                                                                           

[INFO] Creating squashfs filesystem...

Parallel mksquashfs: Using 80 processors
Creating 4.0 filesystem on /tmp/nccl.squash, block size 131072.
[====================================================================================================================================================================|] 2639/2639 100%

Exportable Squashfs 4.0 filesystem, lzo compressed, data block size 131072
	uncompressed data, compressed metadata, compressed fragments, compressed xattrs
	duplicates are removed
Filesystem size 46816.67 Kbytes (45.72 Mbytes)
	74.47% of uncompressed filesystem size (62869.08 Kbytes)
Inode table size 38894 bytes (37.98 Kbytes)
	37.39% of uncompressed inode table size (104027 bytes)
Directory table size 32379 bytes (31.62 Kbytes)
	51.64% of uncompressed directory table size (62701 bytes)
Number of duplicate files found 99
Number of inodes 3163
Number of files 2410
Number of fragments 251
Number of symbolic links  180
Number of device nodes 0
Number of fifo nodes 0
Number of socket nodes 0
Number of directories 573
Number of ids (unique uids + gids) 2
Number of uids 1
	lcapps (11868)
Number of gids 1
	dip (30)

**Comment by lukeyeager** [comment]
This is the issue: https://github.com/NVIDIA/enroot/blob/v1.1.0/bin/enroot-mksquashovlfs.c#L18

We can fix this for our workflow by either:
* Rebuild enroot with e.g. `MOUNTPOINT=/tmp/enroot-mountpint` (anything other than `/mnt`)
* Mount our external shares somewhere that is not masked by the mount at `/mnt` (e.g. `/nfs/scratch/`)
