### ISSUE TITLE
Mounting host filesystem

### ISSUE THREAD

**Issue by airyimbin** [NVIDIA/enroot#104]
Is there a way to prevent users from mounting / or mounting anything from the host filesystem?
Currently you can mount / to the container and then switching to root in the container will expose files like /etc/passwd.

It could be a security risk if users can just mount and view files owned by root.

**Comment by 3XX0** [comment]
No there is currently no way to restrict that.
Mounting things doesn't grant any elevated privileges, if your users can mount `/etc/passwd` and read from it, they can also just read it normally on the host filesystem.

If you want to restrict that, change the permission on the file to not be world readable.
