### ISSUE TITLE
NVIDIA device driver

### ISSUE THREAD

**Issue by arunreddy00** [NVIDIA/enroot#105]
I installed enroot on **_ubuntu 20.04_**.
Also installed pre-requisites with **_latest libnvidia-container-tools for GPU support_**. System met all the requirements. PFA.
![image](https://user-images.githubusercontent.com/58287304/137686494-8ce2439f-24e4-481f-80a7-6c56bcdcf982.png)

When I try to import one of the NVIDIA NGC containers and start the container using enroot. I'm facing below error.

```
 [WARN] Kernel module nvidia_uvm is not loaded. Make sure the NVIDIA device driver is installed and loaded
 nvidia-container-cli: initialization error: driver error: failed to process request
 [ERROR] /usr/local/etc/enroot/hooks.d/98-nvidia.sh exited with return code 1
```

Kindly, help on error .

**Comment by 3XX0** [comment]
The warning is pretty self explanatory, your NVIDIA driver is not fully loaded, the UVM kernel module is missing.

You can `modprobe` it or load it with `sudo nvidia-container-cli -k info`. If you want to make it persistent, you can always create a [systemd service](https://github.com/NVIDIA/nephele/blob/bd404a9f7351f141dff362ccbc4d263bb3c42109/ansible/playbooks/nvidia.yml#L47) for it

**Comment by 3XX0** [comment]
Are you trying to use a GPU? Your machine doesn't have NVIDIA's driver installed.
Refer to https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#driver-installation to install the drivers for your GPU.

**Comment by 3XX0** [comment]
> I installed enroot on **_ubuntu 20.04_**. Also installed pre-requisites with **_latest libnvidia-container-tools for GPU support_**

Why did you install `libnvidia-container-tools` if you don't have GPUs?
Anyhow, you can run a GPU image whitout GPUs by setting `-e NVIDIA_VISIBLE_DEVICES=void` when you run the container.

**Comment by arunreddy00** [comment]
Thank you Jonathan,

It worked.
