### ISSUE TITLE
Gitmodule libbsd is not working - Location moved

### ISSUE THREAD

**Issue by rujschafer** [NVIDIA/enroot#114]
Looks like libbsd is no longer available in the currently configuration location. It has moved to: https://gitlab.freedesktop.org/libbsd/libbsd

**Comment by flx42** [comment]
Per https://libbsd.freedesktop.org/wiki/,  https://anongit.freedesktop.org/git/libbsd.git is still available and it's just a few commits behind the gitlab instance.
Is it not working for you right now?

**Comment by rujschafer** [comment]
Ill go ahead and close the issue. I just happen to do a pull at the wrong time in the early morning hours when the repo happened to be offline. My apologies! Thank you for responding!
