### ISSUE TITLE
aarch64 release for deb linux

### ISSUE THREAD

**Issue by terryjx** [NVIDIA/enroot#121]
I noticed that among the release version, pre-compiled deb file for aarch64 architecture is missing. 

Can we have a aarch64 version sometime soon?

**Comment by 3XX0** [comment]
You mean this?

https://github.com/NVIDIA/enroot/releases/download/v3.4.0/enroot_3.4.0-1_arm64.deb

If you follow the install instructions it should just work

**Comment by terryjx** [comment]
Thanks for the prompt reply, yes, this is what I'm looking for... I think I mistaken arm64 for amd64...
