### ISSUE TITLE
Import and start a Image with just one line.

### ISSUE THREAD

**Issue by likejazz** [NVIDIA/enroot#124]
To start an Ubuntu image from Docker Hub, You should write the three commands as follows:
```
$ enroot import docker://ubuntu
$ enroot create ubuntu.sqsh
$ enroot start ubuntu
```

But this is very verbose and complicated. Especially, engineers don't want to repeat similar commands every time. They want to shrink to just one line as follows:

```
$ enroot start docker://ubuntu
```

This one line command works in the same way as the three-line commands(`import`, `create`, `start`) above. 

How about this?

**Comment by 3XX0** [comment]
While this is not ideal, we want to keep things simple in the current design.
We're thinking about some alternatives in the long run that should ease this process.

Having said that, most users tend to keep the squashfs image around or the container filesystem and reuse those, so you don't generally type these 3 commands every single time.
You could also remove the `create` if you were to use fuse and wanted a temporary container.
The Slurm integration ([pyxis](github.com/nvidia/pyxis)) is also simplifying these steps.
