### ISSUE TITLE
Mount points in enroot containers showing IOs on local device and not on mounted device.

### ISSUE THREAD

**Issue by karanveersingh5623** [NVIDIA/enroot#129]
Hi Team

I am trying to run Beegfs IOR  containers using slurm + pyxis + enroot using local NVMe drive as Beegfs mount point , below is the cmd
![image](https://user-images.githubusercontent.com/30921663/178436156-6d9b2fbd-7376-41b8-949c-04179bca418f.png)

The IOs are not seen in NVMe drive , instead its been showing up in sda and dm-0 [Screenshot attached]. 
![image](https://user-images.githubusercontent.com/30921663/178435864-f2c1b4b2-cba1-4e45-b650-a406f438e389.png)

Please let me know how to change this configuration.

Changed enroot configuration but no effect , below are the details

![image](https://user-images.githubusercontent.com/30921663/178436565-98ad42ae-8c39-4a6f-98ef-0e46f4ce3ae5.png)
![image](https://user-images.githubusercontent.com/30921663/178436831-cb7286dd-5800-430a-bbf8-e54de301b835.png)

The ior test files are getting created but IOs are not seen on mounted device

**Comment by karanveersingh5623** [comment]
Please let me know if more info is needed :)

**Comment by flx42** [comment]
enroot/pyxis should have no impact on this, what happens if you do `srun ior` (or `srun fio`) without containers and on the same mountpoint?

**Comment by karanveersingh5623** [comment]
Found the root , it was burst buffer configuration , thanks for your input , closing the issue
