### ISSUE TITLE
Release Repositories and Expanded Prebuilt RPMs

### ISSUE THREAD

**Issue by nlvw** [NVIDIA/enroot#131]
Hi All,
First of all great work and I hope Nvidia continues to invest in this.

Are there any plans on provided release RPMs as part of a repository to make enroot easier to consume?  The libnvidia-container repo (https://nvidia.github.io/libnvidia-container/) seems to be a good example on how to do this with just GitHub.  An official Spack package recipe would also work though I'm not sure the caps functionality would work from that install method.

If not are the current el7 RPMs compatible with RHEL 8 (or clones)?  For newer RHEL (8/9) will I need to build enroot from source instead?

**Comment by 3XX0** [comment]
We don't currently plan on making a repository for enroot.
Regarding the RPMs, yes the el7 should work on every RHEL based distribution, enroot is statically linked and doesn't depend on any specific userspace aside from standard utilities.
