### ISSUE TITLE
numctl error

### ISSUE THREAD

**Issue by xinyx62** [NVIDIA/enroot#139]
I use nvidia local images:
enroot import dockerd://nvcr.io/nvidia/hpc-benchmarks:21.4-hpl
srun -N 1 --container-image ./nvcr.io+nvidia+hpc-benchmarks+21.4-hpl.sqsh  --pty bash
when run numactl -C 0 ls , it get error:
  
![image](https://user-images.githubusercontent.com/35787534/197675153-d77be4a3-c1a9-422e-8cce-33dcb2f82eaa.png)

while use lscpu, it looks good:
![image](https://user-images.githubusercontent.com/35787534/197675265-14108ef0-87d7-4021-b3a1-f0ad778265c0.png)

I think it is some misconfiguration, but at the moment I am not able to spot it. Thanks.

**Comment by flx42** [comment]
Same as https://github.com/NVIDIA/pyxis/issues/94#issuecomment-1289956480

**Comment by flx42** [comment]
Closing since https://github.com/NVIDIA/pyxis/issues/94 is also closed.
