### ISSUE TITLE
Possible to convert squashed container image back to docker?

### ISSUE THREAD

**Issue by JohannesTheo** [NVIDIA/enroot#145]
Hello, quick question. 

Is there any known way to bring back a squashed container image to the docker world?

Thanks,
Johannes

**Comment by 3XX0** [comment]
Not really no, you can manually unsquash the rootfs and then `docker import` the resulting directory but you're gonna have to translate all the [enroot configuration](https://github.com/NVIDIA/enroot/blob/master/doc/image-format.md) to the docker equivalents (it should be fairly easy to script with the use of `--change`)

**Comment by JohannesTheo** [comment]
Thanks for the quick response! :)
