### ISSUE TITLE
404 Error importing custom image from docker.io 

### ISSUE THREAD

**Issue by rormseth** [NVIDIA/enroot#146]
Hello,
  I am running Enroot 3.4.0 on Rocky 9.0.  When running `enroot import`, I am getting 404 errors for some custom images, but not all.  Here is my error:
```
[user@n1 ~]$ enroot import docker://hpcreid/openmpi:2212228 
[INFO] Querying registry for permission grant
[INFO] Authenticating with user: <anonymous>
[INFO] Authentication succeeded
[INFO] Fetching image manifest list
[INFO] Fetching image manifest
[ERROR] URL https://registry-1.docker.io/v2/hpcreid/openmpi/manifests/2212228 returned error code: 404 Not Found
[user@n1 ~]$ 
```
However, I know that enroot is correctly configured, because all of these work properly:
```
enroot import docker://ubuntu
enroot import docker://rockylinux:8.7 
enroot import docker://gmao/ubuntu20-baselibs:v7.6.1-openmpi_4.1.4-gcc_12.1.0 
```
Can you help me understand why it is failing for the `hpcreid` image, but succeeds for the `gmao` image?

**Comment by 3XX0** [comment]
We only support the Docker format manifest version 2 currently. So chances are, you pushed it using an old version of Docker or Podman with the default OCI format

**Comment by rormseth** [comment]
Yep, that fixed it.  Thanks.
