### ISSUE TITLE
Failure handling nested mounts

### ISSUE THREAD

**Issue by twh** [NVIDIA/enroot#147]
On a host with nested mounts, e.g.,

nfs:/results   /results
lustre:outputs   /results/outputs

Mapping to the container in enroot fails:

/results /results none x-create=dir,rw,nosuid,bind,fs_passno=2 0 0

enroot-mount: failed to mount: /results at /scratch/enroot/data/uid-10000/pyxis_361192.0/results: Invalid argument

**Comment by 3XX0** [comment]
Try without `fs_passno=2`

**Comment by 3XX0** [comment]
Try with just `/results`. Also try to strace the command see what the mount syscall ends up being

**Comment by twh** [comment]
[strace.txt](https://github.com/NVIDIA/enroot/files/10483507/strace.txt)

Included for review, thanks

**Comment by 3XX0** [comment]
Was this with just `/results` in your conf file?
Can you send the output with `strace -f`? It's required to trace the mount processes.

**Comment by twh** [comment]
Ah yes, included here,

[strace.txt](https://github.com/NVIDIA/enroot/files/10513174/strace.txt)

**Comment by 3XX0** [comment]
Yeah looks like a bug, can you try with `/results /results none x-create=dir,rw,nosuid,bind,relatime 0 0`

**Comment by twh** [comment]
Attached:

[strace.txt](https://github.com/NVIDIA/enroot/files/10538423/strace.txt)

**Comment by 3XX0** [comment]
I'm not exactly sure what's happening, can you test: ` enroot-nsenter --user --mount --remap-root mount --bind -o rw,nosuid,bind,relatime /results /mnt` see if it works? If it does, can you send the strace for it?

**Comment by 3XX0** [comment]
FYI I also pushed a fix that could be related to this issue: https://github.com/NVIDIA/enroot/commit/2674fb99ae14d59742781c6c88b28de81afc90fa

If you could test your mount against the `master` branch this would be great.

**Comment by twh** [comment]
I tried unsuccessfully after compiling the latest. I tried spinning up the container as well as the nsenter command. The nsenter command only works with singular mounts that aren't nested.

[strace.txt](https://github.com/NVIDIA/enroot/files/10581632/strace.txt)
[strace-nsenter.txt](https://github.com/NVIDIA/enroot/files/10581634/strace-nsenter.txt)

**Comment by 3XX0** [comment]
Yeah since the mounts are nested you need `rbind` instead of `bind`.
This is the default when not specifying any option (i.e. just `/results`) so this should have worked before, which is why I'm confused.
Maybe you do need the latest *and* to specify `rbind`. 

So hopefully with latest both of those work:
* `/results /results none x-create=dir,rw,nosuid,rbind,relatime 0 0`
* `/results`

**Comment by twh** [comment]
It works when specifying rbind without running latest. This is enough to get us going for now. Thanks.
