### ISSUE TITLE
Will Dockerfile with USER and HEALTHCHECK break enroot container?

### ISSUE THREAD

**Issue by verdimrc** [NVIDIA/enroot#158]
I need to use a security scanner (checkov) on a Dockerfile, and it fails on two checks: missing healthcheck [[ref](https://docs.bridgecrew.io/docs/ensure-that-healthcheck-instructions-have-been-added-to-container-images)], and not adding non-root user [[ref](https://docs.bridgecrew.io/docs/ensure-that-a-user-for-the-container-has-been-created)].

Does anyone know if adding the two recommended instructions are still compatible with enroot? Is there any side effect or different behaviours that I need to be aware of? Thanks.

**Comment by 3XX0** [comment]
You can add them, these won't have any effect with Enroot.

**Comment by verdimrc** [comment]
Thank you!
