### ISSUE TITLE
Run GUI applications?

### ISSUE THREAD

**Issue by biocyberman** [NVIDIA/enroot#16]
Have you guys succeeded with running tensorboard or jupyter nodtebook on SLURM+enroot-driven cluster? If you did, I would like to see an example.

**Comment by 3XX0** [comment]
It's mostly up to the container image, there nothing specific to SLURM/enroot.
You can checkout the NGC images, they have tensorboard included: https://docs.nvidia.com/deeplearning/frameworks/tensorflow-release-notes/rel_19.08.html#rel_19.08

**Comment by biocyberman** [comment]
How port forwarding/binding is done with enroot then? I haven't seen any documentation about this. In Docker: https://runnable.com/docker/binding-docker-ports

**Comment by 3XX0** [comment]
There is no port forwarding in enroot, whatever port your application is listening on is the one you should connect to. 

GUI applications are outside the scope of enroot, it's up to the container image or the admin to figure out what they need and configure whatever is necessary. I don't know what x11docker tries to do, but there are several way to do it, for example:
- VNC (https://gitlab.com/nvidia/container-images/samples/blob/master/opengl/ubuntu16.04/turbovnc-virtualgl/Dockerfile)
- X11 forwarding (e.g. using SLURM)
- Reuse the host Xorg server (e.g. https://github.com/NVIDIA/enroot/blob/master/doc/usage.md#example)

**Comment by ltalirz** [comment]
> Are GUI applications available at this time with enroot?

Yes, as shown in the [linked example](https://github.com/NVIDIA/enroot/blob/master/doc/usage.md#example), here would be how to run `xeyes`:
```
enroot start --env DISPLAY --mount /tmp/.X11-unix:/tmp/.X11-unix ubuntu.sqsh bash
root@host:/# apt update && apt install -y x11-apps
root@host:/# xeyes
```
