### ISSUE TITLE
Dynamic path for TMPDIR env variable

### ISSUE THREAD

**Issue by ashwinidr23** [NVIDIA/enroot#162]
i have enroot installed in our cluster recently. i have modified enroot.conf with relevant paths for runtime, cache etc. 
i wanted to know if there is a way to dynamically change/update the path where TMPDIR env variable is pointing to. updating the prolog epilog scripts are not feasible at the moment as there are other dependencies.

**Comment by 3XX0** [comment]
For enroot itself or inside the container?

The enroot temporary directory is controlled through `ENROOT_TEMP_PATH` which defaults to `TMPDIR` but you can change that. The enroot config is evaluated so you can have dynamic things in there. For example: `ENROOT_TEMP_PATH=/tmp/$(id -u)`

**Comment by ashwinidr23** [comment]
Thanks a lot, I wanted the directory name to be in sync with tmpdir created by slurm when a job gets created. i was not sure if it would pick up this dynamic env variable. but it did work. 
Thanks again!
