### ISSUE TITLE
getting could not process json input while doing enroot import from private aws ecr repo 

### ISSUE THREAD

**Issue by ashokrd-aws** [NVIDIA/enroot#166]
Installed enroot with RHEL distribution 
sudo yum install https://github.com/NVIDIA/enroot/releases/download/v3.4.1/enroot-3.4.1-1.el8.x86_64.rpm
sudo yum install https://github.com/NVIDIA/enroot/releases/download/v3.4.1/enroot+caps-3.4.1-1.el8.x86_64.rpm
Configured .credentials file 
able to authenticate  but getting Could not process JSON input error. 
Error Message:
[INFO] Querying registry for permission grant
[INFO] Authenticating with user: AWS
[INFO] Using credentials from file: /home/ec2-user/enroot/.credentials
[INFO] Authentication succeeded
[INFO] Fetching image manifest list
[ERROR] Could not process JSON input

On another AWS Parallelcluster head node, I installed enroot from source and it is working. 
I am working in private subnet with no internet access, so planning to install it from RHEL distribution.

**Comment by 3XX0** [comment]
There is a fix in master for this but we didn't make a new release of enroot yet. In the meantime you can patch the script manually, the fix is pretty trivial: https://github.com/NVIDIA/enroot/commit/9bc97b16398469c13fc6ed856d92c6ed841c5fde

**Comment by ashokrd-aws** [comment]
Sure. Thank you.

**Comment by sean-smith** [comment]
@3XX0 would you advise we install from `master` - we have a script used to install enroot on AWS ParallelCluster that pins to the last release, see https://github.com/aws-samples/aws-parallelcluster-post-install-scripts/blob/main/pyxis/postinstall.sh#L48

**Comment by 3XX0** [comment]
Either that or you can always patch the script after installing the packages. I will try to release new packages when I find the time.

**Comment by sean-smith** [comment]
Any update on a new enroot release?
