### ISSUE TITLE
The right way to increase ulimit

### ISSUE THREAD

**Issue by verdimrc** [NVIDIA/enroot#167]
To match the `--ulimit stack=xxx` from docker run (below), I found that I need to modify `/etc/security/limits.conf`. Is this the right way?

```bash
docker run --gpus all --ipc=host --ulimit memlock=-1 --ulimit stack=67108864 -it --rm nvcr.io/ea-bignlp/nemofw-training:23.07-py3 /bin/bash
```

Is it possible to set the limit only when I invoke `enroot start ...` ?

**Comment by 3XX0** [comment]
You can set the ulimit the usual way or inside an entrypoint if you want
* `ulimit -s 4096 ; enroot start ubuntu`
* `enroot start --rc <(echo ulimit -s 4096\; bash) ubuntu`

**Comment by verdimrc** [comment]
Thank you.
