### ISSUE TITLE
cgroup memory limit not visible in enroot container via sysfs

### ISSUE THREAD

**Issue by elelayan** [NVIDIA/enroot#169]
On a Debian 11 system (systemd, cgroupsv2), slurm 23.02.6

I'm not sure I understand correctly but it seems the 10-cgroups.sh hook mounts the leaf cgroup, which has no restriction, to `/sys/fs/cgroup`.

on host:

````
root@slurm-worker-1:~# cat /sys/fs/cgroup/system.slice/slurm-worker-1_slurmstepd.scope/job_4749/step_0/user/task_0/memory.max 
max
root@slurm-worker-1:~# cat /sys/fs/cgroup/system.slice/slurm-worker-1_slurmstepd.scope/job_4749/step_0/user/memory.max 
4194304000
````

in container for job 4749:
````
# cat /sys/fs/cgroup/memory.max 
max
`````

I guess programs like nodejs will be confused when sizing their memory depending on the cgroup-allocated memory if they don't have the info.

Is there a reason to do not mount the parent scope?

**Comment by 3XX0** [comment]
Um yeah this looks like Pyxis specific, we probably need to detect this and mount the step cgroup instead of the task one in this case.
I will have to look into this, but you can always try editing the hook yourself.
Something like: `"${mount}/${path#${root}}/.."`

**Comment by elelayan** [comment]
OK, thanks: modifying the hook works for my usecase, where I wanted a way to determine the allocated memory from within the container.

My usecase was remounting /tmp and /dev/shm with size=JOB_ALLOCATED_MEMORY so that I can use more than half the node's ram in tmpfs if needed.

But I wonder if it would be a problem for further cgroup manipulation because inside the container `/proc/self/cgroup` is `0::/` but the current cgroup is really `/sys/fs/cgroup/task_0/`. Just mentioning it in case it's relevant.

**Comment by elelayan** [comment]
thanks
