### ISSUE TITLE
unable to pull gcr images

### ISSUE THREAD

**Issue by stingbe** [NVIDIA/enroot#18]
enroot import docker://gcr.io#google-containers/addon-builder
[INFO] Querying registry for permission grant
[INFO] Found valid credentials in cache
[INFO] Fetching image manifest list
[INFO] Fetching image manifest
[ERROR] URL https://gcr.io/v2/google-containers/addon-builder/manifests/latest returned error code: 401 Unauthorized

I wonder if it's even picking up my credentials file. Even after deleting all the cache and credentials file. It still says found valid credentials in cache. Btw I am able to pull from docker hub but no luck gcr private/public images.

**Comment by 3XX0** [comment]
Um it works for me, the problem you might have is if you switch between public and private because GCR uses different tokens for these. The workaround for now is to delete `~/.cache/enroot/.tokens-$(id -u)/gcr.io` between the pulls.

**Comment by stingbe** [comment]
deleting the tokens worked. Is it possible to make this easy instead of deleting every time?

**Comment by 3XX0** [comment]
Yeah I will push the patch, I already have it in another branch.

**Comment by stingbe** [comment]
that's great. 
oauth tokens for gcr are short lived. 
Is it possible to get the below method working instead of providing the actual token? 

machine gcr.io login oauth2accesstoken password "$(gcloud auth print-access-token)"

**Comment by 3XX0** [comment]
I pushed the fix to master.
As for oauth being short lived, you can use the [json keyfile](https://cloud.google.com/container-registry/docs/advanced-authentication#json_key_file) method instead:

`echo -E "machine gcr.io login _json_key password $(jq -rc '.'  keyfile.json | sed 's/ /\\u0020/g')" >> ~/.config/enroot/.credentials`

Kudos to @lukeyeager for the one liner.

**Comment by stingbe** [comment]
But this would mean creating service account for users.

**Comment by 3XX0** [comment]
https://github.com/NVIDIA/enroot/commit/8b474b43a9f593292c1b8866d73410d14d60c998

Let me know it works for you.

**Comment by stingbe** [comment]
That didn't really work :/

**Comment by 3XX0** [comment]
What does your credentials file look like

**Comment by stingbe** [comment]
machine gcr.io login oauth2accesstoken password $(gcloud auth print-access-token)

I think I need to pull latest version right?

**Comment by 3XX0** [comment]
Yes code is in master and not released yet.

**Comment by 3XX0** [comment]
Closed as fixed since release 3.0
