### ISSUE TITLE
Driver compatibility issues when reusing a container

### ISSUE THREAD

**Issue by Juanjdurillo** [NVIDIA/enroot#186]
### Description
I intend to reuse a container created from an image either for executing a second command within the same container or extending it with new libraries (to later export it as a new sqsh container image). However, I encounter issues when attempting to start the container more than once due to driver incompatibilities.

### Environment
Host driver: 535.161.07
NGC images used: 24.02 for TensorFlow or PyTorch (built for driver version 545.23)
NVIDIA compat package detects compatibility with the host driver initially.

### Error Encountered
When attempting to start the container for the second time, the following error occurs:

```
ERROR: This container was built for NVIDIA Driver Release 545.23 or later, but
version 535.161.07 was detected and compatibility mode is UNAVAILABLE.

```
### Investigation
Upon investigation, it was discovered that the issue is related to a file written within the enroot container the first time it is started, located at /usr/local/cuda-12.3/compat/ named .535.161.07.<hostname>.checked. The presence of this file prevents the environment variable _CUDA_COMPAT_STATUS from being set and causes LD_LIBRARY_PATH to miss /usr/local/cuda/compat/lib.real when the container is started subsequently.

### Resolution Attempted
Two possible workarounds have been identified:

1. Manually Setting Environment Variables: Force the necessary environment variables to exist with the expected value in any process created within an enroot container by writing them into /etc/profile in the container.

2. Removing Compatibility Check File: Removing the mentioned file .535.161.07.<hostname>.checked resolves the issue

### Request for Guidance
Seeking clarification on whether the identified workarounds are appropriate solutions or if there is a recommended approach for transparently managing compatibility issues within enroot containers

**Comment by flx42** [comment]
Hello, this is not done by enroot but it's done by some NGC containers such as pytorch and tensorflow. You should not see the problem with a regular `nvidia/cuda` image from DockerHub.

But I'm not quite sure why the CUDA compatibility mode was marked as unavailable, did you import the image to squashfs on a separate machine than where you are trying to use it?

**Comment by Juanjdurillo** [comment]
You're absolutely right. The issue does not appear with the nvidia/cuda image from DockerHub, pointing to issues probably on the images from NGC. 

> did you import the image to squashfs on a separate machine than where you are trying to use it?

Even in the same machine, as long as that checked file is in the container or created sqsh image out of it, it reports that.

**Comment by flx42** [comment]
It's weird. Can you check `_CUDA_COMPAT_STATUS` when running the container that does the export?
```console
$ nvidia-smi | grep CUDA ; srun --container-image nvcr.io/nvidia/pytorch:24.02-py3 --container-save /lustre/.../pytorch.sqsh bash -c 'env | grep COMPAT ; nvidia-smi | grep CUDA'
| NVIDIA-SMI 535.129.03             Driver Version: 535.129.03   CUDA Version: 12.2     |
pyxis: importing docker image: nvcr.io/nvidia/pytorch:24.02-py3
pyxis: imported docker image: nvcr.io/nvidia/pytorch:24.02-py3
_CUDA_COMPAT_STATUS=CUDA Driver OK
_CUDA_COMPAT_PATH=/usr/local/cuda/compat
| NVIDIA-SMI 535.129.03             Driver Version: 535.129.03   CUDA Version: 12.3     |
pyxis: exported container pyxis_27907_27907.9 to /lustre/.../pytorch.sqsh
```
We can see that we have `CUDA Version: 12.3` inside the container, so CUDA forward compatibility kicked in as expected, and we have `_CUDA_COMPAT_STATUS=CUDA Driver OK`.

And then, reusing the exported container image, we still have `CUDA Version: 12.3`:
```console
$ nvidia-smi | grep CUDA ; srun --container-image /lustre/.../pytorch.sqsh bash -c 'env | grep COMPAT ; nvidia-smi | grep CUDA'
| NVIDIA-SMI 535.129.03             Driver Version: 535.129.03   CUDA Version: 12.2     |
_CUDA_COMPAT_PATH=/usr/local/cuda/compat
| NVIDIA-SMI 535.129.03             Driver Version: 535.129.03   CUDA Version: 12.3     |
```

**Comment by Juanjdurillo** [comment]
I will close this issue. We still have the problem but seems to happen only on selected ngc containers.

**Comment by haok1402** [comment]
We also had the same issue. Launching it the second time triggers this error.
And I can confirm deleting the `.checked` file solves the warning.


We use the following commands to remove that checked file at the start of each run.
You may need to change the CUDA version, depending on the release of your container.

```
echo "" >> /etc/profile
echo "rm -f /usr/local/cuda-12.8/compat/.*.checked" >> /etc/profile
```
