### ISSUE TITLE
Missing package dependencies for build

### ISSUE THREAD

**Issue by thatguymike** [NVIDIA/enroot#19]
At least on my Ubuntu setup, I also needed to install 'automake'

**Comment by 3XX0** [comment]
You mean in the doc right?
For the package build we use `autotools-dev` which I guess does the trick:
https://github.com/NVIDIA/enroot/blob/102be94bbe9b93a4cd310a1b11b2a1443594b625/pkg/debbuild#L17

**Comment by thatguymike** [comment]
Yes, doc update.  I'll get around to a PR
