### ISSUE TITLE
Enroot not following /etc/enroot/enroot.conf

### ISSUE THREAD

**Issue by michaelmyc** [NVIDIA/enroot#190]
I'm using the latest 3.4.1 version of enroot, and I have `/etc/enroot/enroot.conf`configured with the following: 

![image](https://github.com/NVIDIA/enroot/assets/15188392/94f3d437-06c4-48fe-8c8e-ecde837a7a83)

When I run `enroot create`, the directory that was created is not in `ENROOT_DATA_PATH` configured in `enroot.conf`, but rather in `~/.local/share/enroot` (the default location).

When I run `enroot create` with the environment variable `ENROOT_DATA_PATH`, enroot now respect the custom location.

**Comment by 3XX0** [comment]
You can debug what's happening in your setup with `bash -x enroot`

**Comment by michaelmyc** [comment]
Thanks! Seems like enroot is reading `/usr/local/etc/enroot/enroot.conf`. After updating that file everything works.
