### ISSUE TITLE
PPC for 3.5.0 release missing

### ISSUE THREAD

**Issue by krono** [NVIDIA/enroot#194]
Hi, it's great to see the 3.5.0 release but I'm missing the ppc packages.
Did they got lost?

**Comment by 3XX0** [comment]
Yeah unfortunately we stopped shipping prebuilt packages for PPC because we lack the infrastructure to build and validate them easily.
You can always build those from the `pkg/` scripts though.

**Comment by krono** [comment]
That's sad, but understandable, but thanks anyway :)
