### ISSUE TITLE
Switch to lz4 as default squashfs compression?

### ISSUE THREAD

**Issue by thatguymike** [NVIDIA/enroot#20]
For the simple example of 'enroot import 'docker://nvcr.io#nvidia/cuda:10.0-base', moving to lz4 instead of lzo is 2-3x faster in my quick testing and seems to end up with smaller images.  lz4 was not installed by default on my system, but on debian systems, 'sudo apt install liblz4-tool' was all that was required.

**Comment by 3XX0** [comment]
Yeah, we have to keep lzo as a default unfortunately for compatibility with RHEL 7. See https://github.com/NVIDIA/enroot/issues/6.

Zstd nowadays might be better, but might also require newer tooling.
