### ISSUE TITLE
Enroot with NVIDIA MPS?

### ISSUE THREAD

**Issue by scottcs2** [NVIDIA/enroot#206]
Hi,

I am trying to get Enroot to play nicely with NVIDIA MPS. However, I encounter the following problem when running NVIDIA nemo containers using enroot while MPS control daemon is running.

Steps:
```
nvidia-cuda-mps-control -d
export NVIDIA_DRIVER_CAPABILITIES=all
enroot start --root -w --env NVIDIA_DRIVER_CAPABILITIES nemo2
```

Causes this error to be printed:
```
ERROR: The NVIDIA Driver is present, but CUDA failed to initialize.  GPU functionality will not be available.
   [[ Mapping of buffer object failed (error 205) ]]
```

If I kill the MPS daemon, then the container works. How do I use MPS and an enroot container simultaneously?

Thanks,
Scott

**Comment by 3XX0** [comment]
Did you try with a simple CUDA container?
What's your driver version and GPUs inside the container?

You might want to move this issue to https://github.com/NVIDIA/libnvidia-container since it's specific to GPU support.

**Comment by scottcs2** [comment]
The issue is if I specify --root as an enroot argument, then it breaks with NVIDIA MPS. Without --root, the container is able to access the GPUs even with MPS enabled.
