### ISSUE TITLE
`NVIDIA_VISIBLE_DEVICES` used in `enroot/conf/hooks/98-nvidia.sh` is problematic on clusters when only part of GPUs are allocated

### ISSUE THREAD

**Issue by lucifer1004** [NVIDIA/enroot#207]
In the current implementation, for example, when the devices `0,1,4,5` are allocated, the environment variable `NVIDIA_VISIBLE_DEVICES` is kept as is. This becomes problematic when trying to `enroot start`, there will be an error `nvidia-container-cli: device error: 4: unknown device`.

A quick solution is to set `NVIDIA_VISIBLE_DEVICES` according to the length of the device list. In the previous case, it should be set to `0,1,2,3`, and then `enroot start` can work as expected.

**Comment by 3XX0** [comment]
I don't know what you mean by allocated. This is a problem with your setup if you're passing invalid/unavailable GPU ID to enroot.
If you're using Enroot with Slurm+Pyxis, this variable should be set to `all` and handled with GPU gres.

**Comment by lucifer1004** [comment]
Closed as not a bug of `enroot`.
