### ISSUE TITLE
enroot-unshare: failed to disable SSBD mitigation: Numerical result out of range

### ISSUE THREAD

**Issue by romanzac** [NVIDIA/enroot#22]
Hi All,

I am not able to start container on Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-20-generic x86_64). I have tried to configure any possible value for kernel parameter "spec_store_bypass_disable",  however always with the same error. I have no problem on CentOS 7.6.

https://github.com/tyhicks/ssbd-tools/blob/master/README.md

Error log:
0: slurmstepd-gn03: pyxis: importing docker image ...
0: slurmstepd-gn03: pyxis: creating container filesystem ...
0: slurmstepd-gn03: pyxis: starting container ...
0: slurmstepd-gn03: error: pyxis: container start failed with error code: 1
0: slurmstepd-gn03: error: pyxis: printing contents of log file ...
0: slurmstepd-gn03: error: pyxis:     enroot-unshare: failed to disable SSBD mitigation: Numerical result out of range
0: slurmstepd-gn03: error: spank: required plugin spank_pyxis.so: task_init_privileged() failed with rc=-1

Thanks for any suggestions.
R.

**Comment by 3XX0** [comment]
Looks like SSBD settings require 4.15.0-22 (see https://usn.ubuntu.com/3652-1/).
You might want to upgrade your kernel or alternatively you can use the `-hardened` flavor of the packages, these won't try to disable spectre mitigations.

**Comment by romanzac** [comment]
Hi Jonathan,

Many thanks. Kernel upgrade to 4.15.0-74 did a job for me. 

FYI:
Hardened version failed with error:

0: slurmstepd-gn03: pyxis: importing docker image ...
0: slurmstepd-gn03: pyxis: creating container filesystem ...
0: slurmstepd-gn03: pyxis: starting container ...
0: slurmstepd-gn03: error: pyxis: seccomp filter failed: Invalid argument
1: slurmstepd-gn03: error: pyxis: seccomp filter failed: Invalid argument
2: slurmstepd-gn03: error: pyxis: seccomp filter failed: Invalid argument
2: slurmstepd-gn03: error: spank: required plugin spank_pyxis.so: task_init() failed with rc=-1

R.

**Comment by 3XX0** [comment]
No problem, closing as resolved.
The second issue is coming from pyxis, we might need to fix it. Adding @flx42 for visibility
