### ISSUE TITLE
XDG_RUNTIME_DIR

### ISSUE THREAD

**Issue by maxim-belkin** [NVIDIA/enroot#23]
Hi.

I built `enroot` from source (build logs are here: https://gist.github.com/49b9266a7ee0ae1d4383c0e4b3474bbb)

When I execute `enroot`, the following error message pops up:
```sh
mkdir: cannot create directory '/run/enroot': Permission denied
```
It looks like the location `enroot` is trying to use (`/run/enroot`) is controlled by `XDG_RUNTIME_DIR` variable. Is there a way to set this variable in a non-invasive way (that is, without modifying the source code) at the `make install` step?

**Comment by 3XX0** [comment]
It looks like `XDG_RUNTIME_PATH` is not set for your user, you can configure this inside `enroot.conf`, see https://github.com/NVIDIA/enroot/blob/master/doc/configuration.md

**Comment by maxim-belkin** [comment]
Right, I'm testing `enroot` inside of a Docker container and it is not set there.
I can change the config file after `enroot` is installed but I was wondering if there is a way to avoid that step and specify it (on the command line as an argument to `make`) in advance.

**Comment by 3XX0** [comment]
No unfortunately not, you can always set it in the environment of your docker container

**Comment by maxim-belkin** [comment]
Got it, thank you!

**Comment by maxim-belkin** [comment]
A quick follow-up. `enroot.in` defines an absolute value for `XDG_RUNTIME_DIR`:
```
config::export XDG_RUNTIME_DIR         "/run"
```
Why does it do that and not `${XDG_RUNTIME_DIR:-something}`?

**Comment by 3XX0** [comment]
If you look at the function implementation, it does exactly that
