### ISSUE TITLE
HPC installation in every computing node?

### ISSUE THREAD

**Issue by selefant** [NVIDIA/enroot#28]
Hi !

my name is Stefano Elefante and I am working at the Institute of Science and Technology Austria.
I am working in the team whose duty is to administrate the local HPC cluster. 

We are investing possible docker solutions that may be deployed in our HPC cluster. We are very interested in using NVIDIA/enroot. I am writing to you as I would like to know:

1) Do we need to install NVIDIA/enroot in every computing node? 
2) We are using SLURM as workload manager. I suppose NVIDIA/enroot is fully compatible, isn't it?

Kind regards,
Stefano

**Comment by flx42** [comment]
Hello Stefano,

> Do we need to install NVIDIA/enroot in every computing node?

No, you can install enroot only on some nodes if you wish to.

> We are using SLURM as workload manager. I suppose NVIDIA/enroot is fully compatible, isn't it?

Yes it is. It will launch the container within the Slurm cgroups. It is also integrated with PMIx to have Slurm orchestrate multi-node MPI launches.
We also have a [Slurm SPANK plugin](https://github.com/NVIDIA/pyxis) that leverages enroot to provide a simple UX, e.g. `srun --container-image=pytorch`.

You might need to tweak your enroot config for Slurm purposes, for instance in a Slurm prolog. I mentioned some examples here: https://github.com/NVIDIA/pyxis/issues/12#issuecomment-581622017

You can look at our slides/recording from FOSDEM 2020 if you want more details about our stack:
https://fosdem.org/2020/schedule/event/containers_hpc_unprivileged/
