### ISSUE TITLE
Unable to spawn more pty devices

### ISSUE THREAD

**Issue by SpontaneousDuck** [NVIDIA/enroot#29]
I am trying to run a Jupyter Lab instance inside of a container using the continuumio/anaconda3 image. I did the recommended steps for pulling and creating the enroot container image. When running this container in Docker, I am able to do the following:
```
# python
>>> import pty
>>> pty.fork()
(12, 3)
```
But when I do this on my enroot container:
```
# python
>>> import pty
>>> pty.fork()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.7/pty.py", line 96, in fork
    master_fd, slave_fd = openpty()
  File "/opt/conda/lib/python3.7/pty.py", line 29, in openpty
    master_fd, slave_name = _open_terminal()
  File "/opt/conda/lib/python3.7/pty.py", line 59, in _open_terminal
    raise OSError('out of pty devices')
OSError: out of pty devices
>>>
```

This is important to Jupyter in that this is the process it uses to run bash commands or open up an interactive shell.

Thanks for the help!

**Comment by 3XX0** [comment]
What version of enroot are you using? IIRC this was fixed at some point

**Comment by SpontaneousDuck** [comment]
I installed with https://github.com/NVIDIA/ansible-role-enroot to install so that means I am on v2.0.1. Could I just plug in the newer version to that to update?

**Comment by 3XX0** [comment]
Yeah, I'm not really familiar with Ansible, but it should just be a matter of changing these lines: https://github.com/NVIDIA/ansible-role-enroot/blob/master/defaults/main.yml#L14-L15

correct @lukeyeager ?

**Comment by SpontaneousDuck** [comment]
Perfect! I updated to v3.0.2 and that solved the issue. I updated the ansible role and made a PR for updating the version.

**Comment by lukeyeager** [comment]
@SpontaneousDuck will you checkout `v0.2.0` of the `nvidia/enroot` ansible role for me? I just pushed it.
https://galaxy.ansible.com/nvidia/enroot

**Comment by SpontaneousDuck** [comment]
Looks great! Thanks! Did not realize I bumped that PR and then made a separate one haha
