### ISSUE TITLE
how to pass an environment file into enroot container  like --env-file in docker/podman?

### ISSUE THREAD

**Issue by coldbloodx** [NVIDIA/enroot#31]
This can be done by putting the environment file into /etc/enroot/environ.d/, but it's for global enroot configuration, and I want to specify environment file one by one, is there any option can do this?

**Comment by lukeyeager** [comment]
`enroot start -c` provides something similar: https://github.com/NVIDIA/enroot/blob/v3.1.0/doc/cmd/start.md

**Comment by 3XX0** [comment]
@coldbloodx does it work for you?

**Comment by coldbloodx** [comment]
seems it does not work, here is my test:

1. check envfile
[root@rcn04 ~]# cat /tmp/envfile
env1=env1
env2=adfasdf
env3=asdfasd
env4=aaaaa
env5=bbb
env6=ccccc

2. check the rc file
[root@rcn04 ~]# cat test.rc
environ(){
    # Keep all the environment from the host

    . /tmp/envfile
}


rc() {
    exec bash
}

3. run enroot start with -c rcfile.
[root@rcn04 ~]# enroot start --mount /tmp:/tmp --mount /root:/root -c /root/test.rc ubuntu env
root@rcn04:~# env
SHELL=/bin/bash
EDITOR=vim
PWD=/root
LOGNAME=root
HOME=/root
TERM=xterm-256color
USER=root
SHLVL=1
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/bin
_=/usr/bin/env

check mount in container.
root@rcn04:~# ls /tmp/
envfile  pim.info.rcn04  v5jzO5B


Any mistake I made?

**Comment by coldbloodx** [comment]
it does not work even I update the envfile as below:
root@rcn04:~# cat /tmp/envfile
export env1=env1
export env2=adfasdf
export env3=asdfasd
export env4=aaaaa
export env5=bbb
export env6=ccccc
root@rcn04:~# source /tmp/envfile
root@rcn04:~# env |grep env
env2=adfasdf
env3=asdfasd
env1=env1
env6=ccccc
env4=aaaaa
env5=bbb
_=/usr/bin/env

**Comment by 3XX0** [comment]
You can't source the file as it will simply set these variables in the context of the configuration, use `cat` instead:
```
environ(){
    cat /tmp/envfile
}
```

**Comment by coldbloodx** [comment]
it works now~~~ 
thanks~

Please close this ticket 👍
