### ISSUE TITLE
What is fuse-overlayfs required for?

### ISSUE THREAD

**Issue by jfolz** [NVIDIA/enroot#32]
We're on kernel 4.15 and fuse-overlayfs [lists 4.18 as minimum](https://github.com/containers/fuse-overlayfs/tree/800011be8fdffa35f674c984beaeff69d2a5a9f0#requirements), so we cannot install it.
What would be be missing out on without this dependency?

Edit: doubly relevant, since our DGX are also on 4.15 ;)

**Comment by flx42** [comment]
It's required if you want to start a container from a squashfs file directly:
https://github.com/NVIDIA/enroot/blob/master/doc/cmd/start.md#starting-container-images
i.e. it allows you to do that:
```console
$ enroot import docker://ubuntu
$ enroot start ubuntu.sqsh 
```

Without `fuse-overlayfs`, you have to do this:
```
$ enroot import docker://ubuntu
$ enroot create ubuntu.sqsh 
$ enroot start ubuntu
```

**Comment by jfolz** [comment]
I see, thank you. We updated a machine running Ubuntu 18.04.4 to kernel 5.4 and installed a static version of `fuse-overlayfs` 1.1.2 and `squashfuse` 0.1.100 from the repository. Creating the container first and starting it does work as expected (with GPUs etc.), but mounting SquashFS fails:
```
$ enroot start ubuntu.sqsh
[WARN] fuse: unknown option `uid=2039'
[ERROR] Failed to mount: /home/folz/ubuntu.sqsh
```

I guess I'll create new issues for that ;)

**Comment by 3XX0** [comment]
Sorry it's not clear from the documentation but you actually need fuse3 for this to work.
I'll update the instructions

**Comment by jfolz** [comment]
Aha! I thought that might be an issue. We'll see about installing fuse3.

**Comment by jfolz** [comment]
Is there a minimum version required for `squashfuse` as well?

**Comment by 3XX0** [comment]
No as long as everything uses fuse3 you should be good

**Comment by jfolz** [comment]
Managed to get it working by backporting groovy packages for fuse3, fuse-overlayfs and squashfuse to bionic. Turns out that there is no release of squashfuse that supports fuse3 (only master supports it), so fuse2 needs to be installed in parallel.
