### ISSUE TITLE
is there any option to set cwd when enroot container starts?

### ISSUE THREAD

**Issue by coldbloodx** [NVIDIA/enroot#34]
[root@rcn04 ~]# enroot start ubuntu /bin/bash
root@rcn04:/# pwd
/
^^^^
When enroot container starts, the cwd is /, is there any way to set it?

**Comment by 3XX0** [comment]
It doesn't look like we expose it at the moment even though lower level commands like `enroot-nsenter` and `enroot-switchroot` do support it. I guess we could add a new option to the command line.

In the meantime you can always achieve the same thing with a custom entrypoint (i.e. `--rc` or `--conf`) that does the `cd`, or you could implement your own logic with a custom hook with `/etc/rc.local`.

For example:

`~/.config/enroot/hooks.d/10-workdir.sh` (make sure it is executable)
```
#! /bin/sh

if [ -n "${MYWORKDIR-}" ]; then
    echo "cd ${MYWORKDIR}" >  "${ENROOT_RUNTIME_PATH}/rc.local"
    echo "${ENROOT_RUNTIME_PATH}/rc.local /etc/rc.local" >> "${ENROOT_MOUNTS}"
fi
```

Which enables something like `MYWORKDIR=/tmp enroot start ubuntu`

**Comment by coldbloodx** [comment]
@3XX0 

Thank you for the answer.

Hope you can add the option later.

We're integrating our product with enroot these days, below is my thought.

1. user could set cwd by adding his own rc scripts as well, if we have one, and the later one takes effects(the execution order is same as sysV rc, I guess), this'll changes previous cwd setting in rc script. 
2. if we add a rc, this would invade the users environments.


So I think  an enroot option to set cwd is better 👍

**Comment by 3XX0** [comment]
@coldbloodx We could add a new option the problem is that it won't work with Docker imports because `WORKDIR` is currently implemented in `/etc/rc` which will come after we set cwd.

Would this be acceptable for your use case still?

**Comment by krono** [comment]
Hey @3XX0 you closed this some time after the last comment.

Did you ever get around to implement that option?
