### ISSUE TITLE
enroot update container using package manager

### ISSUE THREAD

**Issue by pbtrial** [NVIDIA/enroot#35]
Is it possible to import ubuntu-18.04 docker image to enroot and then install some packages when running the enroot container?
If I do 
`apt install vim`
I get dpkg: error: requested operation requires superuser privilege

If I do
`sudo apt install vim`
I get 
`bash: sudo: command not found`

A solution is to go back and add basic packages to my docker container? Is there an enroot specific way I can do this?

**Comment by 3XX0** [comment]
You can use `--root` and `--rw` to remap yourself as root and have the container writable respectively.
For example:
```
enroot import -o ubuntu.sqsh docker://ubuntu:18.04
enroot create ubuntu.sqsh
enroot start -r -w ubuntu sh -c 'apt update && apt install -y vim-tiny'
enroot start ubuntu vi
```
