### ISSUE TITLE
enroot exit with "0" even the cli contains invalid options.

### ISSUE THREAD

**Issue by coldbloodx** [NVIDIA/enroot#37]
[root@rcn04 ~]# /usr/bin/enroot start --mount /home/lcui:/home/lcui --mount /scratch/lsf_addon/lcui/lsf1011:/scratch/lsf_addon/lcui/lsf1011 --mount /tmp:/tmp --aaa value --rw ubuntu hostname
Usage: enroot start [options] [--] NAME|IMAGE [COMMAND] [ARG...]

Start a container and invoke the command script within its root filesystem.
Command and arguments are passed to the script as input parameters.

In the absence of a command script and if a command was given, it will be executed directly.
Otherwise, an interactive shell will be started within the container.

 Options:
   -c, --conf CONFIG    Specify a configuration script to run before the container starts
   -e, --env KEY[=VAL]  Export an environment variable inside the container
       --rc SCRIPT      Override the command script inside the container
   -r, --root           Ask to be remapped to root inside the container
   -w, --rw             Make the container root filesystem writable
   -m, --mount FSTAB    Perform a mount from the host inside the container (colon-separated)
[root@rcn04 ~]# echo $?
0
^^^^^^^^
should it be non-zero?

Here is result for podman and docker.
root@ucn01:~# docker run -asdf ubuntu hostname
invalid argument "sdf" for "-a, --attach" flag: valid streams are STDIN, STDOUT and STDERR
See 'docker run --help'.
root@ucn01:~# echo $?
125
^^^^^^^

[root@rcn04 ~]# podman run --aaaa centos hostname
Error: unknown flag: --aaaa
[root@rcn04 ~]# echo $?
125
^^^^^

**Comment by 3XX0** [comment]
Yes it is coming from there: https://github.com/NVIDIA/enroot/blob/master/enroot.in#L233
I guess we could change this to a `1`

**Comment by flx42** [comment]
@3XX0 Usually, I think some programs return `0` if you do something like `cmd --help`; but return `1` if you do something like `cmd --aaa`, even if the usage is printed in both cases.
