### ISSUE TITLE
Dockerfile's ENTRYPOINT has priority over [COMMAND] in start mode

### ISSUE THREAD

**Issue by jGsch** [NVIDIA/enroot#38]
If there is an ENTRYPOINT in the Dockerfile, when the container is launched with a command, it will still start in shell mode. But maybe it's deliberate?

```
➜ ~/test cat Dockerfile 
from ubuntu
ENTRYPOINT bash
 ➜ ~/test docker build --tag=test/test:test . && \
enroot import dockerd://test/test:test && \
enroot create -f test+test+test.sqsh
...
 ➜ enroot start test+test+test echo "HELLO"
jgsch@SERVER:/$ 
```

```
➜ ~/test cat Dockerfile 
from ubuntu
 ➜ ~/test docker build --tag=test/test:test . && \
enroot import dockerd://test/test:test && \
enroot create -f test+test+test.sqsh
...
 ➜ enroot start test+test+test echo "HELLO"
HELLO
```

**Comment by lukeyeager** [comment]
That's expected. A "normal" entrypoint would be something like this:
```bash
#!/bin/bash
# do stuff ...
exec "$@"
```
Yours doesn't exec the args from the CMD - it ignores them and just runs bash.

Your issue is with the Dockerfile format - not with enroot. Try `docker run --rm -it test/test:test echo "HELLO"` if you don't believe me.

**Comment by jGsch** [comment]
@lukeyeager OK! Thanks for the explanation!

**Comment by 3XX0** [comment]
FYI Enroot tries to mimic the Docker behavior documented here:
https://docs.docker.com/engine/reference/builder/#understand-how-cmd-and-entrypoint-interact

You can look at `/etc/rc` inside the container to see how it works exactly (it's getting converted here https://github.com/NVIDIA/enroot/blob/master/src/docker.sh#L222-L226)
