### ISSUE TITLE
enroot start:  No space left on device

### ISSUE THREAD

**Issue by coldbloodx** [NVIDIA/enroot#39]
xianwu@haswell04[~]:$df -h /home/xianwu/
Filesystem Size Used Avail Use% Mounted on
**filerb.eng.platformlab.ibm.com:/vol/vol2/xianwu 2.0G 618M 1.4G 31% /home/xianwu**

xianwu@haswell04[]:$ll /tmp/cuda.sqsh
-rw-r--r-- 1 root root 3584847872 Sep 24 01:35 /tmp/cuda.sqsh
xianwu@haswell04[]:$ll -h /tmp/cuda.sqsh
**-rw-r--r-- 1 root root 3.4G Sep 24 01:35 /tmp/cuda.sqsh**

xianwu@haswell04[~]:$enroot create --name cuda /tmp/cuda.sqsh
**[INFO] Extracting squashfs filesystem...

Parallel unsquashfs: Using 88 processors
10471 inodes (37434 blocks) to write

[=============================================================================================================|] 37434/37434 100%

created 9690 files
created 1373 directories
created 776 symlinks
created 0 devices
created 0 fifos**

xianwu@haswell04[]:$enroot list -f
NAME PID STATE STARTED TIME MNTNS USERNS COMMAND
**cuda. --> image is created successfully.**
ubuntu
xianwu@haswell04[]:$

**xianwu@haswell04[~]:$enroot start cuda hostname
sed: couldn't close stdout: No space left on device
[ERROR] /etc/enroot/hooks.d/10-shadow.sh exited with return code 4**

xianwu@haswell04[]:$df -h /home/xianwu/
Filesystem Size Used Avail Use% Mounted on
**filerb.eng.platformlab.ibm.com:/vol/vol2/xianwu 2.0G 2.0G 0 100% /home/xianwu. --> no space.**
xianwu@haswell04[]:$

**Comment by coldbloodx** [comment]
xianwu@haswell04[~]:$df -h /home/xianwu/
Filesystem                                       Size  Used Avail Use% Mounted on
**filerb.eng.platformlab.ibm.com:/vol/vol2/xianwu  2.0G  618M  1.4G  31% /home/xianwu**

xianwu@haswell04[~]:$ll /tmp/cuda.sqsh
**-rw-r--r-- 1 root root 3584847872 Sep 24 01:35 /tmp/cuda.sqsh**
xianwu@haswell04[~]:$ll -h /tmp/cuda.sqsh
**-rw-r--r-- 1 root root 3.4G Sep 24 01:35 /tmp/cuda.sqsh**

xianwu@haswell04[~]:$enroot create --name cuda /tmp/cuda.sqsh
**[INFO] Extracting squashfs filesystem...

Parallel unsquashfs: Using 88 processors
10471 inodes (37434 blocks) to write

[=============================================================================================================|] 37434/37434 100%

created 9690 files
created 1373 directories
created 776 symlinks
created 0 devices
created 0 fifos**

xianwu@haswell04[~]:$enroot list -f
NAME    PID  STATE  STARTED  TIME  MNTNS  USERNS  COMMAND
**cuda**. --> image is created successfully.
ubuntu
xianwu@haswell04[~]:$

xianwu@haswell04[~]:$enroot start cuda hostname
**sed: couldn't close stdout: No space left on device**
**[ERROR] /etc/enroot/hooks.d/10-shadow.sh exited with return code 4**

xianwu@haswell04[~]:$df -h /home/xianwu/
Filesystem                                       Size  Used Avail Use% Mounted on
**filerb.eng.platformlab.ibm.com:/vol/vol2/xianwu  2.0G  2.0G     0 100% /home/xianwu. --> no space.**
xianwu@haswell04[~]:$

**Comment by 3XX0** [comment]
The shadow hook needs to write to the container filesystem to setup the use shadow database.
In your case it fails because your home directory is full and it is the default for `ENROOT_DATA_PATH`.
You can change the storage of container by setting the `ENROOT_DATA_PATH` environment variable or modifying `/etc/enroot/enroot.conf`

**Comment by li-li-github** [comment]
Hi @3XX0 , I get the same error when I perform `enroot bundle` due to the `/tmp` folder size limitation. Is there any ways to change the temporary path for enroot bundle?
