### ISSUE TITLE
enroot-nsenter: failed to create user namespace: Invalid argument

### ISSUE THREAD

**Issue by mathrock74** [NVIDIA/enroot#41]
I'm trying to build a deepops test environment with 2 KVM worker VMs (CentOS 7) with 1 V100D-8Q vGPU and 64G RAM each. I don't know if that makes sense, but for Kubernetes it worked mostly. For slurm I followed https://github.com/NVIDIA/deepops/blob/master/docs/deepops/dgx-pod.md#7-deploy-slurm, which also worked (with some modifications because of different NVIDIA driver for vGPU). 

Now I want to "Verify Pyxis and Enroot can run GPU jobs across all nodes." (https://github.com/NVIDIA/deepops/tree/master/docs/slurm-cluster). The command that's run by ansible is:
srun -N 2 -G 2 --ntasks-per-node=1 --mpi=pmix --exclusive  --container-image=deepops/nccl-tests-tf20.06-ubuntu18.04:latest all_reduce_perf -b 1M -e 4G -f 2 -g 1

It fails with:
    pyxis: creating container filesystem ...
    pyxis: starting container ...
    slurmstepd: error: pyxis: container start failed with error code: 1
    slurmstepd: error: pyxis: printing contents of log file ...
    slurmstepd: error: pyxis:     enroot-nsenter: failed to create user namespace: Invalid argument
    slurmstepd: error: pyxis: couldn't start container
    slurmstepd: error: pyxis: if the image has an unusual entrypoint, try using --no-container-entrypoint
    slurmstepd: error: spank: required plugin spank_pyxis.so: task_init() failed with rc=-1
    slurmstepd: error: Failed to invoke spank plugin stack
    srun: error: deepops-node1: task 0: Exited with exit code 1

I'm very new to Slurm/pyxis/enroot, so I don't know what to make of "enroot-nsenter: failed to create user namespace: Invalid argument" and how to debug this. Any help appreciated, thank you very much.

**Comment by 3XX0** [comment]
Your kernel is probably not configured properly, on Centos 7 there are things you need to turn on and I don't think Deepops does it automatically.

Refer to the following: https://github.com/NVIDIA/enroot/blob/master/doc/requirements.md

**Comment by mathrock74** [comment]
Thanks for pointing me to this, setting the right kernel parameters and sysctls solved the problem.
