### ISSUE TITLE
seccomp issues in enroot container

### ISSUE THREAD

**Issue by gfrogat** [NVIDIA/enroot#43]
Hi,

I am having some issues running a Docker container https://github.com/LPDI-EPFL/masif/blob/master/docker_tutorial.md via `enroot v3.1.1` getting `Bad system call (core dumped)` when I run a static binary ([`reduce`](http://kinemage.biochem.duke.edu/software/reduce.php)).

The program successfully runs outside enroot and when I run the container using Docker. What's strange is that `reduce` also successfully runs if the enroot container is run via `pyxis v0.8.1` on our SLURM cluster.

As far as I understand it, the problem is likely related to the seccomp filter set here
https://github.com/NVIDIA/enroot/blob/98dca83d5a94d94b60831f39a19e7ff85d00b74d/bin/enroot-nsenter.c#L253-L263

Pyxis seems to set its seccomp filters differently which probably makes it work there https://github.com/NVIDIA/pyxis/blob/5d6d9a3657e853b32bb790dc7a89dc4d60ea0c8c/seccomp_filter.h#L70-L79

Is there a simple way to change the seccomp filter for enroot to get `reduce` also to work locally (without running via pyxis and SLURM)?

~~I already tried to compile enroot from source with `-DALLOW_SPECULATION` because I thought `SECCOMP_FILTER_FLAG_SPEC_ALLOW` might set some additional permissions. But this didn't help (but I might have messed up somewhere)~~ edit: just realized this is probably not relevant for this.

Thank you

### `enroot-check --verify`:
```bash
Kernel version:

Linux version 4.18.0-193.28.1.el8_2.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 8.3.1 20191121 (Red Hat 8.3.1-5) (GCC)) #1 SMP Thu Oct 22 00:20:22 UTC 2020

Kernel configuration:

CONFIG_NAMESPACES                 : OK
CONFIG_USER_NS                    : OK
CONFIG_SECCOMP_FILTER             : OK
CONFIG_OVERLAY_FS                 : OK (module)
CONFIG_X86_VSYSCALL_EMULATION     : OK
CONFIG_VSYSCALL_EMULATE           : KO (required if glibc <= 2.13)
CONFIG_VSYSCALL_NATIVE            : KO (required if glibc <= 2.13)

Kernel command line:

vsyscall=native                   : KO (required if glibc <= 2.13)
vsyscall=emulate                  : OK

Kernel parameters:

user.max_user_namespaces          : OK
user.max_mnt_namespaces           : OK

Extra packages:

nvidia-container-cli              : OK
```

### `strace reduce` | enroot:

```bash
execve("./reduce.3.23.130521.linuxi386", ["./reduce.3.23.130521.linuxi386"], 0x7ffdd8653080 /* 15 vars */) = 0
strace: [ Process PID=38139 runs in 32 bit mode. ]
uname( <unfinished ...>)                = ?
+++ killed by SIGSYS (core dumped) +++
Bad system call (core dumped)
```

### `strace reduce` | baremetal:

```bash
execve("./reduce.3.23.130521.linuxi386", ["./reduce.3.23.130521.linuxi386"], 0x7ffde750e800 /* 26 vars */) = 0
strace: [ Process PID=37676 runs in 32 bit mode. ]
uname({sysname="Linux", nodename="localhost.localdomain", ...}) = 0
brk(NULL)                               = 0x885b000
brk(0x885bcb0)                          = 0x885bcb0
set_thread_area({entry_number=-1, base_addr=0x885b830, limit=0x0fffff, seg_32bit=1, contents=0, read_exec_only=0, limit_in_pages=1, seg_not_present=0, useable=1}) = 0 (entry_number=12)
brk(0x887ccb0)                          = 0x887ccb0
brk(0x887d000)                          = 0x887d000
stat64("reduce_wwPDB_het_dict.txt", 0xff8af580) = -1 ENOENT (No such file or directory)
write(2, "reduce: version 3.23 05/21/2013,"..., 69reduce: version 3.23 05/21/2013, Copyright 1997-2013, J. Michael Word) = 69
write(2, "\n", 1
)                       = 1
write(2, "reduce.3.23.130521", 18reduce.3.23.130521)      = 18
write(2, "\n", 1
)                       = 1
write(2, "arguments: [-flags] filename or "..., 33arguments: [-flags] filename or -) = 33
write(2, "\n", 1
)                       = 1
write(2, "\n", 1
)                       = 1
write(2, "Suggested usage:", 16Suggested usage:)        = 16
write(2, "\n", 1
)                       = 1
write(2, "reduce -FLIP myfile.pdb > myfile"..., 53reduce -FLIP myfile.pdb > myfileFH.pdb (do NQH-flips)) = 53
write(2, "\n", 1
)                       = 1
write(2, "reduce -NOFLIP myfile.pdb > myfi"..., 61reduce -NOFLIP myfile.pdb > myfileH.pdb (do NOT do NQH-flips)) = 61
write(2, "\n", 1
)                       = 1
write(2, "\n", 1
)                       = 1
write(2, "Flags:", 6Flags:)                   = 6
write(2, "\n", 1
)                       = 1
write(2, "-FLIP             add H and rota"..., 54-FLIP             add H and rotate and flip NQH groups) = 54
write(2, "\n", 1
)                       = 1
write(2, "-NOFLIP           add H and rota"..., 59-NOFLIP           add H and rotate groups with no NQH flips) = 59
write(2, "\n", 1
)                       = 1
write(2, "-Trim             remove (rather"..., 52-Trim             remove (rather than add) hydrogens) = 52
write(2, "\n", 1
)                       = 1
write(2, "\n", 1
)                       = 1
write(2, "-NOBUILD#.#       build with a g"..., 61-NOBUILD#.#       build with a given penalty often 200 or 999) = 61
write(2, "\n", 1
)                       = 1
write(2, "-BUILD            add H, includi"..., 73-BUILD            add H, including His sc NH, then rotate and flip groups) = 73
write(2, "\n", 1
)                       = 1
write(2, "                  (except for pr"..., 71                  (except for pre-existing methionine methyl hydrogens)) = 71
write(2, "\n", 1
)                       = 1
write(2, "\n", 1
)                       = 1
write(2, "\n", 1
)                       = 1
write(2, "-STRING           pass reduce a "..., 75-STRING           pass reduce a string object from a script, must be quoted) = 75
write(2, "\n", 1
)                       = 1
write(2, "usage: from within a script, red"..., 71usage: from within a script, reduce -STRING "_name_of_string_variable_") = 71
write(2, "\n", 1
)                       = 1
write(2, "\n", 1
)                       = 1
write(2, "-Quiet            do not write e"..., 56-Quiet            do not write extra info to the console) = 56
write(2, "\n", 1
)                       = 1
write(2, "-REFerence        display citati"..., 44-REFerence        display citation reference) = 44
write(2, "\n", 1
)                       = 1
write(2, "-Version          display the ve"..., 47-Version          display the version of reduce) = 47
write(2, "\n", 1
)                       = 1
write(2, "-Changes          display the ch"..., 40-Changes          display the change log) = 40
write(2, "\n", 1
)                       = 1
write(2, "-Help             the more exten"..., 74-Help             the more extensive description of command line arguments) = 74
write(2, "\n", 1
)                       = 1
exit_group(1)                           = ?
+++ exited with 1 +++
```

**Comment by flx42** [comment]
Hello @gfrogat, thanks for the bug report.

First of all, I see that you are using a x86 (32-bit) binary:
> strace: [ Process PID=38139 runs in 32 bit mode. ]

This arch is not supported by our seccomp filter, so it will return `SECCOMP_RET_KILL`:
https://github.com/NVIDIA/enroot/blob/98dca83d5a94d94b60831f39a19e7ff85d00b74d/bin/enroot-nsenter.c#L96-L98

Pyxis and enroot use the same seccomp filter, but have a different logic for applying them.
Enroot applies the seccomp filter when user namespaces are involved, whether or not you remap root (`enroot start --root`).
Pyxis applies the seccomp filter only when remapping root (`srun --container-remap-root`, which might be the default depending on your enroot configuration). So that should explain the difference in behavior you are mentioning.

I will let @3XX0 comment on why it always apply the seccomp filter.

With enroot:
```
$ echo -e 'int main() {}' | gcc -xc - -m32 -o ~/main32 -static

$ enroot start ubuntu+20.04 bash -c 'id -u ; grep Seccomp /proc/self/status ; ~/main32'
1000
Seccomp:        2
bash: line 1: 3810894 Bad system call         ~/main32

$ enroot start --root ubuntu+20.04 bash -c 'id -u ; grep Seccomp /proc/self/status ; ~/main32'
0
Seccomp:        2
bash: line 1: 3811067 Bad system call         ~/main32
```

With pyxis:
```
$ srun --container-image ubuntu:20.04 --no-container-remap-root bash -c 'id -u ; grep Seccomp /proc/self/status ; ~/main32'
1000
Seccomp:        0 
# Works fine

$ srun --container-image ubuntu:20.04 --container-remap-root bash -c 'id -u ; grep Seccomp /proc/self/status ; ~/main32'
Seccomp:        2
/usr/bin/bash: line 1: 3812901 Bad system call         ~/main32
```

You can see that pyxis also fails when remapping root, since the seccomp filter is also applied. Can you confirm that's also the case for you @gfrogat?

**Comment by gfrogat** [comment]
> This arch is not supported by our seccomp filter, so it will return SECCOMP_RET_KILL:
>
> [Code Block]
> 
> Pyxis and enroot use the same seccomp filter, but have a different logic for applying them.
Enroot applies the seccomp filter when user namespaces are involved, whether or not you remap root (enroot start --root).
Pyxis applies the seccomp filter only when remapping root (srun --container-remap-root, which might be the default depending on your enroot configuration). So that should explain the difference in behavior you are mentioning.

Thank you, your explanation makes everything more clear. I wasn't aware of the issues with the 32bit programs. I thought this might be already addressed by the `CONFIG_X86_VSYSCALL_EMULATION` kernel configuration option mentioned in the requirements.

> You can see that pyxis also fails when remapping root, since the seccomp filter is also applied. Can you confirm that's also the case for you @gfrogat?

Yes, it also fails when I set `--container-remap-root` when using pyxis + SLURM.
