### ISSUE TITLE
How to run enroot in a managed K8s?

### ISSUE THREAD

**Issue by elgalu** [NVIDIA/enroot#45]
Hi, how to setup enroot kernel config in a [customized Kubernetes setup](https://github.com/zalando-incubator/kubernetes-on-aws)? Or perhaps this is not possible when running in a K8s unprivileged pod?

```sh
./enroot-check_*.run --verify
[ERROR] Could not find kernel configuration
```

```sh
cat /proc/sys/user/max_user_namespaces
3062836

cat /proc/sys/user/max_mnt_namespaces
3062836

cat /proc/sys/kernel/unprivileged_userns_clone
1
```

**Comment by 3XX0** [comment]
Unfortunately this is not possible unprivileged because docker will block it through seccomp amongst other things. You could relax the seccomp filters though which should be safe if you're truly unprivileged.

**Comment by elgalu** [comment]
Thanks, do you know exactly how to configure my K8s Pod securityContext similar to https://github.com/containers/podman/issues/8130#issuecomment-717232821 perhaps by leveraging `seccomp.security.alpha.kubernetes.io` ?

**Comment by 3XX0** [comment]
Yeah maybe, I'm not really familiar with the new seccomp profiles in K8s.
You will most likely have to whitelist at least `unshare` and `mount`, probably a few other ones

**Comment by 3XX0** [comment]
Any update? Could you make it work?

**Comment by elgalu** [comment]
Gave up on K8s, we'll go with SLURM + plain EC2.
