### ISSUE TITLE
missing enroot-check_3.2.0_x86_64.run in 3.2.0 release

### ISSUE THREAD

**Issue by kcgthb** [NVIDIA/enroot#46]
Just a quick note to let you know that:

```
$ curl -fSsL -O https://github.com/NVIDIA/enroot/releases/download/v3.2.0/enroot-check_3.2.0_$(uname -m).run
curl: (22) The requested URL returned error: 404 Not Found
```
![image](https://user-images.githubusercontent.com/186807/101963541-d1d52380-3bc3-11eb-8130-0bd043f1bf32.png)

Looks like the x86_64 version of the check script is still version 3.1.1 in 3.2.0.

Thanks!

**Comment by 3XX0** [comment]
My bad, thanks for reporting, it should be fixed now

**Comment by kcgthb** [comment]
Thanks for the quick fix!
