### ISSUE TITLE
error in starting enroot container for gromacs:2020.2 on v100 cards

### ISSUE THREAD

**Issue by KapilS25** [NVIDIA/enroot#47]
Getting below mentioned error for : enroot start --rw gromacs:2020.2

nvidia-container-cli: mount error: stat failed: /dev/nvidia-modeset: no such file or directory
[ERROR] /home/apps/centos7/enroot/3.2.0/etc/enroot/hooks.d/98-nvidia.sh exited with return code 1

Checked with the solution provided at : https://github.com/NVIDIA/enroot/issues/15
Setting NVIDIA_DRIVER_CAPABILITIES=utility  gives another error

ERROR Failed to verify GPU driver: GPU driver verification failed: Failed to parse host GPU driver version Malformed version:
FATAL Please double check that GPU passthrough is enabled: `--nv` (Singularity), `--gpus all` (Docker)

GPU Info : Name :  Tesla V100   Driver Version: 450.51.05    CUDA Version: 11.0

**Comment by 3XX0** [comment]
Looks like a problem with the entrypoint of the image, you can use `--rc` to bypass it in the meantime.
@AdamSimpson any idea what's going on?

**Comment by 3XX0** [comment]
Did you manage to solve the issue?

**Comment by KapilS25** [comment]
Issue still persist.

**Comment by AdamSimpson** [comment]
It looks like you're missing the `compute` capability in the workaround. Can you please set `NVIDIA_DRIVER_CAPABILITIES=utility,compute` and try again?

This issue has been resolved internally and will be present in the next gromacs NGC release, thanks for reporting.

**Comment by KapilS25** [comment]
Resolved.
