### ISSUE TITLE
How to configure enroot with PBS Pro 19

### ISSUE THREAD

**Issue by KapilS25** [NVIDIA/enroot#48]
Please provide guidelines to setup enroot with PBS , for interactive as well as batch job (mutinode)

**Comment by 3XX0** [comment]
I'm not really familiar with PBS, if it supports PMIx you can try to wire it up with a hook for multinode jobs.
For example this is how we do it for SLURM: https://github.com/NVIDIA/enroot/blob/master/conf/hooks/extra/50-slurm-pmi.sh

You can also get a look at our [SLURM plugin](https://github.com/NVIDIA/pyxis) to see how enroot has been integrated.

**Comment by KapilS25** [comment]
Hi, I am happy to inform you that i am successfully  able to configure enroot with PBS using instructions provided at https://github.com/NVIDIA/enroot, with some customization/scripts
and with the threads
https://github.com/NVIDIA/enroot/issues/49
https://github.com/NVIDIA/enroot/issues/54

Thanks for your active responses.

**Comment by KapilS25** [comment]
Thanks for your active responses.
