### ISSUE TITLE
How to run enroot instance on multiple nodes , in order to run multinode job using container.

### ISSUE THREAD

**Issue by KapilS25** [NVIDIA/enroot#49]
We want to run mutinode mpi job using enroot, the nodes are interconnected with each other using infiniband , password less ssh is also enabled ,  the problem is that when we are trying to run multinode job from one of the node ,the mpirun is not able to get the same container environment on the other nodes . Please guide us for the above mentioned scenario, in order to activate same enroot container environment on multiple node.

**Comment by 3XX0** [comment]
Do you have an example? What do you mean exactly by
> the mpirun is not able to get the same container environment on the other nodes

Using mpirun with `enroot start` is not going to be ideal as it will create a container per rank, while it's definitely doable it might get messy and you will probably want to write a hook for OpenMPI's PMIx.

We usually recommend using SLURM with [Pyxis](https://github.com/NVIDIA/pyxis) as it will take care of a lot of things, and enroot ships an optional [hook for PMIx](https://github.com/NVIDIA/enroot/blob/master/conf/hooks/extra/50-slurm-pmi.sh).
You can look [here](https://github.com/NVIDIA/deepops) and [here](https://github.com/NVIDIA/nephele) for setting this up.

**Comment by KapilS25** [comment]
Thanks for the prompt response :), i will check with your suggestions.

Do you have an example? What do you mean exactly by the mpirun is not able to get the same container environment on the other nodes
>>
Example : I have two nodes, say  node1 & node2 (40 processors each), where password less ssh is enabled which is required for mpirun to run job on multiple nodes.

Lets say , i am on node1 from where i am starting the job which i expected to run on node1 & node 2
machines is a file containing name node1 & node2 (hostfile for mpirun)
enroot create --name qe6.6a1 $CONTAINER/hpc+quantum_espresso+v6.6a1.sqsh
enroot start --rw  qe6.6a1
mpirun -np 80 -hostfile machines  pw.x -inp test1.in

#Will end up in the below mentioned error , because the container environment is not visible on other node i.e node2,  
We are having working multinode non container applications (as all nodes are sharing the comman storage path) ,
Thats why i want to know how the filesytem inside the container will be visible other nodes.
Single node job using container is working absolutely fine, i.e   mpirun -np 40   pw.x -inp test1.in

bash: orted: command not found
--------------------------------------------------------------------------
ORTE was unable to reliably start one or more daemons.
This usually is caused by:

* not finding the required libraries and/or binaries on
  one or more nodes. Please check your PATH and LD_LIBRARY_PATH
  settings, or configure OMPI with --enable-orterun-prefix-by-default

* lack of authority to execute on one or more specified nodes.
  Please verify your allocation and authorities.

* the inability to write startup files into /tmp (--tmpdir/orte_tmpdir_base).
  Please check with your sys admin to determine the correct location to use.

*  compilation of the orted with dynamic libraries when static are required
  (e.g., on Cray). Please check your configure cmd line and consider using
  one of the contrib/platform definitions for your system type.

* an inability to create a connection back to mpirun due to a
  lack of common network interfaces and/or no route found between
  them. Please check network connectivity (including firewalls
  and network routing requirements).
--------------------------------------------------------------------------

**Comment by 3XX0** [comment]
What you're trying to do is a little complicated, you first need to create the container on all the machines.
If you have a shared filesystem I suggest you set `ENROOT_DATA_PATH` to a shared location.
Once the container filesystem is visible on all the machine you will need to have mpirun start orted inside it.

So it might look something like this:
```bash
# Create the container in the shared filesystem, thus visible on all the machine
export ENROOT_DATA_PATH=/path/to/shared/nfs
enroot create --name mycontainer myimage.sqsh

enroot start -e OMPI_MCA_orte_launch_agent='enroot start mycontainer orted' mycontainer mpirun -hostfile machines ...
```

The environment variable `OMPI_MCA_orte_launch_agent` should tell `mpirun` how to start orted, so we need to use enroot there too.

**Comment by KapilS25** [comment]
Thanks , I will check with this.

**Comment by 3XX0** [comment]
Yes as long as you use OpenMPI and run `mpirun` from within the container.

To make it easier you can configure  `ENROOT_DATA_PATH` in `/etc/enroot/enroot.conf`

You can also create a hook that sets the environment variable automatically (either in `~/.config/enroot/hooks.d` for your user or `/etc/enroot/hooks.d` for all containers). Something like this:

`/etc/enroot/hooks.d/ompi.sh`
```bash
#! /bin/bash

echo "OMPI_MCA_orte_launch_agent=enroot start ${ENROOT_ROOTFS##*/} orted" >> "${ENROOT_ENVIRON}"
```

After these, the following will work out of the box:
```bash
enroot create --name mycontainer myimage.sqsh
enroot start mycontainer mpirun ...
```

**Comment by KapilS25** [comment]
> 
> 
> Thanks , It worked,
> Is the above mentioned step is same for all the mpi applications ?

Hi, there are still some issue with  this, will update you with details soon.

**Comment by KapilS25** [comment]
Hi ,
creating a hook  /etc/enroot/hooks.d/ompi.sh (executable) with 
#! /bin/bash

echo "OMPI_MCA_orte_launch_agent=enroot start ${ENROOT_ROOTFS##*/} orted" >> "${ENROOT_ENVIRON}"

is not working 
command line is working fine.

**Comment by 3XX0** [comment]
Are you sure the path is right and the executable bit correctly set?
Can you start a container and check that the environment variable is indeed not there

You can add something like `echo "Executing ompi.sh" >&2` in the hook to see if it is correctly executed when running containers

**Comment by KapilS25** [comment]
Sorry I made small mistake, the script was not an executable , its working.
Thanks again.

**Comment by KapilS25** [comment]
Hi , following the above discussion, is there similar kind of hook required for other mpi implementation like mpich, mvapich, intelmpi, if yes, how to do that.

**Comment by 3XX0** [comment]
Not really, your best bet is going to be PMIx but it's going to depend on the server being used (e.g. orted for OMPI).
We have one for SLURM, not sure if PBS supports PMIx too.

You probably would have to write your own enroot hook depending on your use case

**Comment by KapilS25** [comment]
Okay.

**Comment by scvance** [comment]
Hey guys, I am running into a similar issue. I want to run a NCCL speed test from between multiple nodes using enroot. My issue is that when I use the orted command as shown above, my second container starts up and throws an error
```
/opt/nvidia/entrypoint.d/50-gpu-driver-check.sh: line 5: ldconfig: command not found

WARNING: The NVIDIA Driver was not detected.  GPU functionality will not be available.
   Use the NVIDIA Container Toolkit to start this container with GPU support; see
   https://docs.nvidia.com/datacenter/cloud-native/ .

[dw-1-5.rc.byu.edu:43288] [[INVALID],INVALID] ORTE_ERROR_LOG: Not found in file ess_env_module.c at line 135
[dw-1-5.rc.byu.edu:43288] [[INVALID],INVALID] ORTE_ERROR_LOG: Bad parameter in file util/session_dir.c at line 107
[dw-1-5.rc.byu.edu:43288] [[INVALID],INVALID] ORTE_ERROR_LOG: Bad parameter in file util/session_dir.c at line 346
[dw-1-5.rc.byu.edu:43288] [[INVALID],INVALID] ORTE_ERROR_LOG: Bad parameter in file base/ess_base_std_orted.c at line 264
```

**Comment by j3soon** [comment]
Thanks for the information! We've successfully configured enroot (without Slurm and Pyxis) to run HPL with MPI on our multi-node cluster. We've documented the steps here for potential future reference: https://github.com/j3soon/multi-node-enroot-without-pyxis-and-slurm
