### ISSUE TITLE
Problem in enroot working with cgroups

### ISSUE THREAD

**Issue by KapilS25** [NVIDIA/enroot#54]
Getting following error with enroot while using with cgroups.

enroot  start --rw   lammps
nvidia-container-cli: mount error: open failed: /scratch/pbs/enroot-data/user-609.chas052/lammps/sys/fs/cgroup/devices/user.slice/devices.allow: permission denied

/scratch/pbs/enroot-data/user-609.chas052/lammps  is our enroot data path

Below is the directory structure , having all required permission, please let us know where it is going wrong.

 ll lammps/
total 80
drwxr-xr-x  2 skapil.vfaculty cc_vfaculty 4096 Oct 19  2018 bin
drwxr-xr-x  2 skapil.vfaculty cc_vfaculty 4096 Apr 24  2018 boot
drwxr-xr-x  2 skapil.vfaculty cc_vfaculty 4096 Oct 19  2018 dev
drwxr-xr-x 38 skapil.vfaculty cc_vfaculty 4096 Jan 11 12:55 etc
drwxr-xr-x  2 skapil.vfaculty cc_vfaculty 4096 Apr 24  2018 home
drwxr-xr-x  2 skapil.vfaculty cc_vfaculty 4096 Jan 11 12:55 host_pwd
drwxr-xr-x  8 skapil.vfaculty cc_vfaculty 4096 Oct 19  2018 lib
drwxr-xr-x  2 skapil.vfaculty cc_vfaculty 4096 Oct 19  2018 lib64
drwxr-xr-x  2 skapil.vfaculty cc_vfaculty 4096 Oct 19  2018 media
drwxr-xr-x  2 skapil.vfaculty cc_vfaculty 4096 Oct 19  2018 mnt
drwxr-xr-x  2 skapil.vfaculty cc_vfaculty 4096 Oct 19  2018 opt
drwxr-xr-x  2 skapil.vfaculty cc_vfaculty 4096 Apr 24  2018 proc
drwx------  2 skapil.vfaculty cc_vfaculty 4096 Oct 19  2018 root
drwxr-xr-x  5 skapil.vfaculty cc_vfaculty 4096 Oct 19  2018 run
drwxr-xr-x  2 skapil.vfaculty cc_vfaculty 4096 Oct 19  2018 sbin
drwxr-xr-x  2 skapil.vfaculty cc_vfaculty 4096 Oct 19  2018 srv
drwxr-xr-x  2 skapil.vfaculty cc_vfaculty 4096 Apr 24  2018 sys
drwxrwxrwt  2 skapil.vfaculty cc_vfaculty 4096 Nov 14  2018 tmp
drwxr-xr-x 10 skapil.vfaculty cc_vfaculty 4096 Oct 19  2018 usr
drwxr-xr-x 11 skapil.vfaculty cc_vfaculty 4096 Oct 19  2018 var
[skapil.vfaculty@vsky003 /scratch/pbs/enroot-data/user-610.chas052]
$ ls -ld  lammps/
drwxr-xr-x 22 skapil.vfaculty cc_vfaculty 4096 Jan 11 12:55 lammps/

**Comment by 3XX0** [comment]
Did you change the nvidia hook? It's configured not to use cgroups by default: https://github.com/NVIDIA/enroot/blob/d133e239170fe92d3288fb6ebd9d85ba4fb82ef5/conf/hooks/98-nvidia.sh#L30

**Comment by KapilS25** [comment]
Yes,
I removed --no-cgroups from nvidia hook.

**Comment by 3XX0** [comment]
Enroot is unprivileged so you won't be able to setup cgroups from it. If you want to restrict resources for your user, I suggest you use something on top like a systemd slice or a resource manager (e.g. SLURM), enroot will inherit the parent cgroup.

**Comment by KapilS25** [comment]
Yes , we are using PBS as resource manager,
The current scenario  is 
1. Without  cgroups at PBS level, & with --no-cgroups in nvidia hook, everything is working fine, but the problem is , enroot is interfering with the other resources which are not allocated to it thats why we wants to use cgroups.
2. With cgroups at PBS level & with --no-cgroups in nvidia hook , enroot start will give the following error,
enroot  start --rw   lammps

**nvidia-container-cli: mount error: file creation failed: /scratch/pbs/enroot-data/user-612.chas052/lammps/dev/nvidia-uvm-tools: operation not permitted**

3. With cgroups at PBS level & removing --no-cgroups in nvidia hook , enroot start will give the following error,
enroot start --rw lammps

**nvidia-container-cli: mount error: open failed: /scratch/pbs/enroot-data/user-613.chas052/lammps/sys/fs/cgroup/devices/pbspro.slice/pbspro-613.chas052.slice/devices.allow: permission denied
[ERROR] /home/apps/centos7/enroot/3.2.0/etc/enroot/hooks.d/98-nvidia.sh exited with return code 1**

Enroot data path is set to : /scratch/pbs/enroot-data/user-613.chas052
/sys/fs/cgroup/devices/pbspro.slice/pbspro-613.chas052.slice/devices.allow  on the host is something which is dealing with cgroups at PBS level 

fstab entries in the enroots etc/enroot/mounts.d/10-system.fstab are as follows
/proc               /proc              none    x-create=dir,rbind,rw,nosuid,nodev,noexec,rslave   0   -1
/sys                /sys               none    x-create=dir,rbind,ro,nosuid,nodev,noexec,rslave   0   -1
/dev                /dev               none    x-create=dir,rbind,rw,nosuid,noexec,rslave         0   -1
tmpfs               /tmp               tmpfs   x-create=dir,rw,nosuid,nodev,mode=755,slave        0   -1
tmpfs               /var/run           tmpfs   x-create=dir,rw,nosuid,nodev,mode=755,slave        0   -1
tmpfs               /var/lock          tmpfs   x-create=dir,rw,nosuid,nodev,mode=755,slave        0   -1
/dev/shm            /dev/shm           none    x-create=dir,bind,rw,nosuid,nodev,noexec,rslave    0   -1

So /sys  on the host need to get mounted inside container at the same path /sys , but at enroot data path ,lammps/sys  is an empty directory.

Please suggest if any changes modifications etc are required in the configuration. Looking forward for solution from your side.

**Comment by 3XX0** [comment]
The scenario 2 should work, you might be missing some permission under the `/scratch/pbs/enroot-data/user-613.chas052/lammps/dev` path. Are you doing anything to the rootfs after `enroot create` has been called by your user?

Can you check that you're able to `touch` a file under this directory?
Also check the permission of the `/dev/nvidia-uvm-tools` on the host

**Comment by KapilS25** [comment]
Are you doing anything to the rootfs after enroot create has been called by your user?
> No.

Can you check that you're able to touch a file under this directory?
>Yes

check the permission of the /dev/nvidia-uvm-tools on the host
>ls -ld /dev/nvidia-uvm-tools
crw-rw-rw- 1 root root 229, 1 Dec 21 12:17 /dev/nvidia-uvm-tools

**Comment by 3XX0** [comment]
This might be a bug with https://github.com/NVIDIA/libnvidia-container
By default `/dev` should be mounted inside the container and should be identical to the host, so no file should be created.
Can you try disabling the hook with `NVIDIA_VISIBLE_DEVICES=void`, once inside the container check that `/dev/nvidia-uvm-tools` matches what you expect.

Enroot also supports isolating devices by creating a new instance of `devtmpfs` you can turn it on with `ENROOT_RESTRICT_DEV=y`. This should solve your problem even though that shouldn't be required.

**Comment by 3XX0** [comment]
BTW if you don't use `ENROOT_RESTRICT_DEV=y`, adding `"--no-devbind"` to the `cli_args` would also solve the issue as a workaround since all the devices should already be there

**Comment by KapilS25** [comment]
1.
export NVIDIA_VISIBLE_DEVICES=void
enroot  start --rw   lammps
2021/01/18 16:03:36 Failed to determine GPU architecture path: Failed to detect GPU Architecture: libnvidia-ml.so not available

where libnvidia-ml.so is present at /usr/lib/libnvidia-ml.so which is present in LD_LIBRARY_PATH 

2.
export ENROOT_RESTRICT_DEV=y
enroot  start --rw   lammps
enroot-mount: failed to mount: devpts at /scratch/pbs/enroot-data/user-613.chas052/lammps/dev/pts: Invalid argument
[ERROR] /home/apps/centos7/enroot/3.2.0/etc/enroot/hooks.d/10-devices.sh exited with return code 1

**3. adding "--no-devbind" to the cli_args
It worked, thank you so much for your help :)**

**Comment by 3XX0** [comment]
For 1, looks like lammps has an entrypoint that queries the GPU so to bypass it you would have to do
`enroot start --rw --rc <(echo bash) lammps` for example, then you can check what's going on inside.

For 2, this is another intersting error, what kernel are you running? Looks like something is not supported.

Glad 3 works, you might want to cross reference this issue on https://github.com/NVIDIA/libnvidia-container to make sure they are aware, this shouldn't be necessary to specify this flag.

**Comment by KapilS25** [comment]
For 1, looks like lammps has an entrypoint that queries the GPU so to bypass it you would have to do
enroot start --rw --rc <(echo bash) lammps for example, then you can check what's going on inside.
Ans : I will check with this.

For 2, this is another intersting error, what kernel are you running? Looks like something is not supported. ?
Ans :
Operating System: CentOS Linux 7 (Core)
Kernel: Linux 3.10.0-957.el7.x86_64

Glad 3 works, you might want to cross reference this issue on https://github.com/NVIDIA/libnvidia-container to make sure they are aware, this shouldn't be necessary to specify this flag. ?
Ans : Sure , i will do that.

It was nice talking with you :)

**Comment by KapilS25** [comment]
For 1, looks like lammps has an entrypoint that queries the GPU so to bypass it you would have to do
enroot start --rw --rc <(echo bash) lammps for example, then you can check what's going on inside.
Ans : 
export NVIDIA_VISIBLE_DEVICES=void
enroot start --rw --rc <(echo bash) lammps
cp: cannot stat ‘/dev/fd/63’: No such file or directory 

Glad 3 works, you might want to cross reference this issue on https://github.com/NVIDIA/libnvidia-container to make sure they are aware, this shouldn't be necessary to specify this flag. ?
Ans : Done. https://github.com/NVIDIA/libnvidia-container/issues/125

**Comment by 3XX0** [comment]
> export NVIDIA_VISIBLE_DEVICES=void
> enroot start --rw --rc <(echo bash) lammps
> cp: cannot stat ‘/dev/fd/63’: No such file or directory

You must have installed the `hardened` version of enroot, which won't let pass fds to the runtime.
You can always use a file for your entrypoint:
```bash
echo bash > entrypoint
enroot start --rw --rc entrypoint
```

I follow up on the libnvidia-container issue.

**Comment by KapilS25** [comment]
Q. You must have installed the hardened version of enroot ?
Ans : Enroot is installed from source (git clone --recurse-submodules https://github.com/NVIDIA/enroot.git) ,even with all its depedencies from source ,


 Q. You can always use a file for your entrypoint ? 
Ans : 
export NVIDIA_VISIBLE_DEVICES=void
echo bash > entrypoint
enroot start --rw --rc entrypoint

**It worked.**

**Comment by KapilS25** [comment]
Hi , the above mentioned issue is resolved , may be  the information is useful for you in some other cases.
The issue was associated with sshrc present at /etc/ssh which is different inside the container. In our case sshrc is using /etc/pbs.conf for managing things associated with the PBS.
Adding  below mentioned line in **/etc/enroot/mounts.d/10-system.fstab**
**/etc/ssh            /etc/ssh           none    x-create=dir,rbind,ro,nosuid,nodev,noexec,rslave   0   -1**  
& Adding  below mentioned line in **/etc/enroot/mounts.d/20-config.fstab** 
**/etc/pbs.conf       /etc/pbs.conf       none    x-create=file,bind,ro,nosuid,nodev,noexec,private                0   -1**
Resolved the issue. :)

**Comment by developermohit06996** [comment]
Hi, I am getting the following error during run the GUI application inside the container, 
 enroot start --wr -r  yade_01
Using python version: 3.8.10 (default, May 26 2023, 14:05:08)
[GCC 9.4.0]
X11 connection rejected because of wrong authentication. (it seems that root file system is not writable), Please let me if any info is required from my side.
