### ISSUE TITLE
gpu choice

### ISSUE THREAD

**Issue by jGsch** [NVIDIA/enroot#55]
I can't prevent access to all gpus with standard hooks.

```
export NVIDIA_VISIBLE_DEVICES=0
enroot start --env NVIDIA_AVAILABLE_DEVICES cuda-container
```

I took the hook given by [nvidia-container-runtime](https://github.com/NVIDIA/nvidia-container-runtime/#environment-variables-oci-spec) but once in the container, `nvidia-smi` still gives informations for all gpus.

**Comment by 3XX0** [comment]
By default enroot exposes all devices, to change this behavior you can set `ENROOT_RESTRICT_DEV` to control the [device hook](https://github.com/NVIDIA/enroot/blob/master/doc/standard-hooks.md#10-devicessh).
After that `NVIDIA_VISIBLE_DEVICES` should work.

Another way to do it is to use cgroups in your resource manager (e.g. systemd, slurm, etc).

**Comment by jGsch** [comment]
@3XX0 Thanks for the answer!

But I think he doesn't understand something about the startup script. When I try to use the launch version, nothing happens:

```
➜ ~ enroot import 'docker://nvidia/cuda:10.0-base' && enroot create --name cuda nvidia+cuda+10.0-base.sqsh

➜ ~ cat script                          
#ENROOT_REMAP_ROOT=y
#ENROOT_RESTRICT_DEV=y

mounts() {
    echo "${PWD} /mnt none bind"
}

environ() {
  NVIDIA_VISIBLE_DEVICES=0
}

rc() {
    exec bash
}

➜ ~ enroot start --rc script cuda  
➜ ~ 
```
Whereas without the script, I get into the prompt:
```
➜ ~ enroot start cuda            
jgsch@SERVER:/$ 
```

I tried to change the rights on the `script` file (`chmod +x script`) but it doesn't seem to change anything. What am I missing?

```
➜ ~ enroot version               
3.2.0
```

**Comment by 3XX0** [comment]
@jGsch `enroot start --rc` expect a [rc](https://github.com/NVIDIA/enroot/blob/master/doc/image-format.md) script, this can be used to specify an entrypoint for the container.

What you wrote on the other hand is a configuration script, you can use `--conf` or `enroot batch` (with `#ENROOT_ROOTFS`) to start your container with it.

**Comment by jGsch** [comment]
@3XX0 Aaaaah OK! It's working now. Thank you for taking the time!
