### ISSUE TITLE
Support for A100 MIG

### ISSUE THREAD

**Issue by elgalu** [NVIDIA/enroot#58]
I've seen https://github.com/NVIDIA/enroot/commit/c3922846cb18ebe614d1c845315e801b3006c4a6 but it's still no clear to me if enroot already fully supports "A100 GPU to be securely partitioned into up to seven separate GPU Instances"

> MIG supports containers using Docker Engine
https://docs.nvidia.com/datacenter/tesla/mig-user-guide/index.html

The article doesn't mention enroot.

**Comment by klueska** [comment]
MIG support in the NVIDIA container stack is implemented in a low-level library called `libvnidia-container`.

Here is a summary of changes that were made to support it:
https://docs.google.com/document/d/13LyeFxuWLSwDjCXKx7RyWWRZEAqA-mghtK3GRPvGv1s/edit

This document walks through examples with docker, but as far as I know, `enroot` also uses `libnvidia-container` under the hood, so should be able to leverage these features as well.

**Comment by 3XX0** [comment]
Enroot does support MIG, you can use the usual `NVIDIA_VISIBLE_DEVICES` envvar and select which instance is passed through, this is similar to docker.
The commit https://github.com/NVIDIA/enroot/commit/c3922846cb18ebe614d1c845315e801b3006c4a6 adds support for configuring MIG *inside* the enroot container. For this you will need to set [NVIDIA_MIG_CONFIG_DEVICES](https://github.com/NVIDIA/nvidia-container-runtime#nvidia_mig_config_devices)

**Comment by 3XX0** [comment]
BTW @elgalu, I forgot to mention that there is also an extra hook that we ship for MIG:
https://github.com/NVIDIA/enroot/blob/master/conf/hooks/extra/50-mig-config.sh

This will automatically toggle the configure bit if the GPU is visible in the container and MIG is enabled on said GPU.
