### ISSUE TITLE
Squashfs image uses lzo compression

### ISSUE THREAD

**Issue by lukeyeager** [NVIDIA/enroot#6]
Am I missing something? 
```console
$ enroot import docker://ubuntu
$ enroot start ubuntu.sqsh 
[WARN] Squashfs image uses lzo compression, this version supports only xz, zlib, lz4, zstd.
[ERROR] Failed to mount: /tmp/tmp.qdpNZdmXxx/ubuntu.sqsh
```
I already have `fuse-overlayfs` and `squashfuse` installed. 

> https://github.com/NVIDIA/enroot/blob/v1.1.0/doc/cmd/start.md#starting-container-images

**Comment by 3XX0** [comment]
Yeah unfortunately lzo is the default because images need to run on RHEL7 (which doesn't support lz4 in base). You can change this by setting `ENROOT_SQUASH_OPTIONS` to `-comp lz4 -noD` if you don't care about the RHEL portability and want to start images directly.

**Comment by lukeyeager** [comment]
Excellent, thanks!
```console
$ ENROOT_SQUASH_OPTIONS='-comp lz4 -noD' enroot import docker://ubuntu
$ enroot start ubuntu.sqsh
```
