### ISSUE TITLE
Enroot usage

### ISSUE THREAD

**Issue by abhisheks1460** [NVIDIA/enroot#60]
Could you please share a basic ,how we can use enroot with example from scratch for docker container which can be use by user without root privilege .

I want to user tenserflow and pyTorch docker container with enroot

**Comment by 3XX0** [comment]
There is an example [here](https://github.com/NVIDIA/enroot/blob/master/doc/usage.md#example)
But basically:
```bash
# import the pytorch image
enroot import -o pytorch.sqsh docker://nvcr.io#nvidia/pytorch:20.12-py3

# create a container from this image
enroot create pytorch.sqsh

# start a command inside it
enroot start pytorch python

# (optionally) if you want to be remapped root and write access inside the container
enroot start --root --rw pytorch sh -c 'apt-get update && apt-get install ...'
```
