### ISSUE TITLE
Unable to install enroor from sources due to git submodule update issue

### ISSUE THREAD

**Issue by gunju** [NVIDIA/enroot#62]
Hi, 
I am trying to install enroot from sources for centos 7.

While running the command 'Sudo make install', I am getting following error:

Clone of 'git://git.musl-libc.org/musl' into submodule path 'deps/musl' failed

Do I have to configure some things first?

**Comment by krono** [comment]
That should work.
What is the output of this?
```bash
cd $(mktemp -d)
git clone git://git.musl-libc.org/musl
```

When this worked, just try your command again.
When not, there might be network problems, as `git://` uses a specific port.

**Comment by 3XX0** [comment]
Looks like a temporary network error, feel free to reopen if you're still hitting this.
