### ISSUE TITLE
Missing package in RHEL-based distributions prerequisite 

### ISSUE THREAD

**Issue by MrBr-github** [NVIDIA/enroot#67]
`rpmlint` should be mentioned as a prerequisite in [From Source](https://github.com/NVIDIA/enroot/blob/v3.2.0/doc/installation.md#from-source) section of the installation document

otherwise `make rpm` fails with below error
```
Executing(%clean): /bin/sh -e /var/tmp/rpm-tmp.rRaWqx
+ umask 022
+ cd /tmp/tmp.EZPwX2vI9v/enroot/pkg/rpm/BUILD
+ /usr/bin/rm -rf /tmp/tmp.EZPwX2vI9v/enroot/pkg/rpm/BUILDROOT/enroot-3.2.0-1.el7.x86_64
+ exit 0
Executing(--clean): /bin/sh -e /var/tmp/rpm-tmp.9Kjrp5
+ umask 022
+ cd /tmp/tmp.EZPwX2vI9v/enroot/pkg/rpm/BUILD
+ exit 0
rpmlint pkg/rpm/RPMS/*
/bin/sh: rpmlint: command not found
make: [rpm] Error 127 (ignored)
rm -f -r pkg/rpm/BUILDROOT pkg/rpm/SOURCES
```

**Comment by 3XX0** [comment]
`rpmlint` is not a prerequisite, this is just a linter helpul for development purposes, users shouldn't need to install it.
The error is ignored as shown in the output above.
