### ISSUE TITLE
Unable to import from private registry or GCR.

### ISSUE THREAD

**Issue by dchirikov** [NVIDIA/enroot#70]
If I run from private registry I get:
```
# enroot import 'docker://master:5000#busybox'
[INFO] Querying registry for permission grant
[ERROR] URL https://master:5000/v2/library/busybox/manifests/latest returned error code: 404 Not Found
```
Same if I try to import from GCR:
```
# enroot import 'docker://gcr.io#google-containers/busybox'
[INFO] Querying registry for permission grant
[INFO] Permission granted
[INFO] Fetching image manifest list
[INFO] Fetching image manifest
[ERROR] URL https://gcr.io/v2/google-containers/busybox/manifests/latest returned error code: 404 Not Found
```
I built it from master branch 2 days ago.

**Comment by flx42** [comment]
Looks like this busybox image on gcr.io was pushed 6+ years ago. As a result, it looks like they don't have an up-to-date image manifest for this container image. enroot supports only manifest v2 schema 2, see https://docs.docker.com/registry/spec/deprecated-schema-v1/

A more recent image should work fine:
```
enroot import docker://gcr.io#deeplearning-platform-release/base-cpu
```

It's probably the same going on with your private registry.

**Comment by lukeyeager** [comment]
The issue with your local registry is that you need to add a `/` in your image name. e.g. `local/busybox` instead of just `busybox`. See how it automatically added "library"? You don't want that. Also discussed here: https://github.com/NVIDIA/enroot/issues/7#issuecomment-499955713.

**Comment by dchirikov** [comment]
@flx42 
Enroot log clearly says url returned 404:
```
[ERROR] URL https://gcr.io/v2/google-containers/busybox/manifests/latest returned error code: 404 Not Found
```
while this link works just fine:
```
curl -I -s https://gcr.io/v2/google-containers/busybox/manifests/latest | head -1
HTTP/1.1 200 OK
```
This is misleading.

@lukeyeager
Local registry indeed does not support v2, and I think it worth mentioning it in the error message instead of generic 404 message. Or, better, to warn when the user tries to feed image without `/`

**Comment by flx42** [comment]
> This is misleading.

I agree this is confusing, but we didn't expect a public registry to not be able to serve a v2 schema 2 manifest, since it has been around for a long time.
Here is the command-line showing the problem with curl:
```
$ curl -H 'Accept: application/vnd.docker.distribution.manifest.v2+json' https://gcr.io/v2/google-containers/busybox/manifests/latest
{"errors":[{"code":"MANIFEST_UNKNOWN","message":"Manifest with tag 'latest' has media type 'application/vnd.docker.distribution.manifest.v1+prettyjws', but client accepts 'application/vnd.docker.distribution.manifest.v2+json'."}]}
```

Whereas a slightly more recent busybox tag, 1.27, works fine:
```
$ curl -H 'Accept: application/vnd.docker.distribution.manifest.v2+json' https://gcr.io/v2/google-containers/busybox/manifests/1.27
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
```

**Comment by dchirikov** [comment]
@flx42 
Ah. Now I see, thanks. Still think it worth displaying manifest incompatibility to the user. It might reduce the amount of opened tickets at least.

**Comment by 3XX0** [comment]
Schema v1 has been deprecated for a while now, and I don't really feel comfortable adding more logic to the already complex import script.
Closing for now, but we might revisit if it's a recurring issue for users
