### ISSUE TITLE
Git cloning error with Connection time out

### ISSUE THREAD

**Issue by moonsooyoung** [NVIDIA/enroot#71]
Helllo,

While trying to clone enroot from Github, I met time out error as below:

git clone --recurse-submodules https://github.com/NVIDIA/enroot.git
...
Cloning into '/mnt/enroot/deps/libbsd'...
fatal: unable to access 'https://anongit.freedesktop.org/git/libbsd.git/': Failed to connect to anongit.freedesktop.org port 443: Connection timed out
fatal: clone of 'https://anongit.freedesktop.org/git/libbsd.git' into submodule path '/mnt/enroot/deps/libbsd' failed
Failed to clone 'deps/libbsd' a second time, aborting

**Comment by 3XX0** [comment]
They might have problems on their main git repository.
You can change it to gitlab instead for the time being:

```
git clone https://github.com/NVIDIA/enroot.git
sed -i 's;anongit.freedesktop.org/git;gitlab.freedesktop.org/libbsd;' .gitmodules
git submodule sync --recursive
git submodule sync --recursive
```

**Comment by moonsooyoung** [comment]
It works perfect. Thank you for the advice, Jonathan.
