### ISSUE TITLE
not able to Compile the nbody sample inside the container 

### ISSUE THREAD

**Issue by abhisheks1460** [NVIDIA/enroot#73]
I m trying to  execute the usage example  below

# Import the CUDA 10.0 image from NVIDIA GPU Cloud
$ enroot import 'docker://$oauthtoken@nvcr.io#nvidia/cuda:10.0-base'

# Create a container out of it
$ enroot create --name cuda nvidia+cuda+10.0-base.sqsh
$ enroot list
cuda

# Compile the nbody sample inside the container
$ enroot start --root --rw cuda sh -c 'apt update && apt install -y cuda-samples-10.0'

Here i m getting below error.

**dgx-cn:/etc/apt/sources.list.d$ enroot start --root --rw cuda sh -c 'apt update && apt install -y cuda-samples-10.0'**
Err:1 http://archive.ubuntu.com/ubuntu bionic InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:2 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease
  Temporary failure resolving 'developer.download.nvidia.com'
Err:3 http://security.ubuntu.com/ubuntu bionic-security InRelease
  Temporary failure resolving 'security.ubuntu.com'
Err:4 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:5 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  InRelease
  Temporary failure resolving 'developer.download.nvidia.com'
Err:6 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
W: No sandbox user '_apt' on the system, can not drop privileges
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic-updates/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic-backports/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/bionic-security/InRelease  Temporary failure resolving 'security.ubuntu.com'
W: Failed to fetch https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/InRelease  Temporary failure resolving 'developer.download.nvidia.com'
W: Failed to fetch https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/InRelease  Temporary failure resolving 'developer.download.nvidia.com'
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package cuda-samples-10.0
E: Couldn't find any package by glob 'cuda-samples-10.0'
E: Couldn't find any package by regex 'cuda-samples-10.0'

**Comment by abhisheks1460** [comment]
I have a requirement to use enroot in my project on DGX A100.

Could you please share a proper step by step learing and usage for Enroot for CUDA,Tenserflow,Pyaxis,Pytroch.slurm and importing containers from NGC and enroot them .

**Comment by 3XX0** [comment]
Looks like you have DNS issues, can you resolve these domain on your host? Do you have any specific DNS config?

**Comment by abhisheks1460** [comment]
We are using proxy ....no dns problem

**Comment by 3XX0** [comment]
You should configure it in the container accordingly then
