### ISSUE TITLE
enroot usage for GROMACS and tenserflow

### ISSUE THREAD

**Issue by abhisheks1460** [NVIDIA/enroot#74]
Can you give the enroot process for tenserflow and GROMACS  docker containers for DGX a100

**Comment by flx42** [comment]
Hello,

You can try importing the GROMACS or TensorFlow images published by NVIDIA here:
https://ngc.nvidia.com/catalog/containers/hpc:gromacs
https://ngc.nvidia.com/catalog/containers/nvidia:tensorflow 

But you will have to adapt those instructions for enroot.

**Comment by abhisheks1460** [comment]
which instruction need to adopt .......those in enroot github page or ngc catalog page

**Comment by flx42** [comment]
The NGC instructions need to be modified when using enroot as the container runtime.

**Comment by harikesh228** [comment]
Unable to find instructions and steps to be carried out, please fill in the details.

**Comment by bilke** [comment]
@harikesh228 What about using your own head to fill in the details?
