### ISSUE TITLE
Can enroot be configured to support docker private registry with self signed certificate?

### ISSUE THREAD

**Issue by billcsm** [NVIDIA/enroot#75]
I tried to import docker image from private registry to enroot, but failed at SSL certificate problem:

enroot import 'docker://admin@hub.com#busybox:latest'
[INFO] Querying registry for permission grant
curl: (60) SSL certificate problem: self signed certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

Can enroot be configured to support docker private registry with self signed certificate? 
Thank you!

**Comment by 3XX0** [comment]
You should be able to configure the `SSL_CERT_` variables in `enroot.conf` or in your environment.

**Comment by billcsm** [comment]
I have created the self signed certificate and saved in /etc/docker/certs.d/hub.com/ca.crt. And I used curl to test it:

$ curl  https://hub.com/v2/_catalog
curl: (60) SSL certificate problem: self signed certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

$ curl --cacert /etc/docker/certs.d/hub.com/ca.crt https://hub.com/v2/_catalog
{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"registry","Class":"","Name":"catalog","Action":"*"}]}]}

But I setup the following SSL_CERT_ variables in /etc/enroot.conf,

SSL_CERT_DIR               /etc/docker/certs.d/hub.com
SSL_CERT_FILE              ca.crt

When I ran enroot import 'docker://admin@hub.com#busybox:latest', I still got the same error. Is my SSL_CERT_ variables setup correct? Thank you.

**Comment by 3XX0** [comment]
You should only use one of the other, for the file one it should be an absolute path.

And again if you use a directory, make sure that the directory has been rehashed.

Note that you can test these variables with curl similarly

**Comment by billcsm** [comment]
Thank you for your help. After I setup the SSL_CERT_FILE in /etc/enroot.conf, it failed at "http" error.

$ enroot import 'docker://admin@hub.com#busybox:latest'
[INFO] Querying registry for permission grant
[INFO] Authenticating with user: admin
Enter host password for user 'admin':
curl: (1) Protocol "http" not supported or disabled in libcurl

I used curl to test hub.com with HTTP and HTTPS:

$ curl --cacert /etc/docker/certs.d/hub.com/ca.crt https://hub.com/v2/_catalog
{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"registry","Class":"","Name":"catalog","Action":"*"}]}]}

$ curl --cacert /etc/docker/certs.d/hub.com/ca.crt http://hub.com/v2/_catalog
curl: (7) Failed to connect to hub.com port 80: Connection refused

The ENROOT_ALLOW_HTTP has been set to "no" in enroot.conf. Should I disable other variables in enroot.conf?  Thank you.

**Comment by 3XX0** [comment]
It looks like it's trying to go through http at some point (maybe a redirect), if so yes you would need `ENROOT_ALLOW_HTTP`

**Comment by billcsm** [comment]
It works with ENROOT_ALLOW_HTTP yes. Thank you a lot for your help!
