### ISSUE TITLE
create enroot container out of local image stored in the file system

### ISSUE THREAD

**Issue by hannesk95** [NVIDIA/enroot#78]
Hello,

I was wondering whether it is possible to create an enroot container out of a local image (i.e. which was created by a command like "docker save" for example)?

Why is this important for me: I can only create a docker container on my local machine, however, this container should be deployed on a different machine where I do not have internet access. On the machine, where I do not have internet access, I can only deploy enroot containers but not docker containers. 

Is there a possible way to transfer the docker image (e.g. using a hard drive / USB stick) to the machine without internet access, and running the "enroot import" command in order to build the enroot container? If yes, how does this "enroot import" command looks like in this case?

I'm grateful for any help! Thank you!

**Comment by 3XX0** [comment]
You can use `enroot import` with the `dockerd://` scheme, this will import from your local Docker daemon (similar to `docker save`) 
You can then copy the resulting squashfs wherever you want and create containers out of it with `enroot create` on the other machine

**Comment by hannesk95** [comment]
Make sense, thank you for your response!

**Comment by jonasteuwen** [comment]
Yes, but it still would be a useful feature to import it from the output of `docker save`. You might not want to allow unprivileged users to build containers on your system (requiring as far as I know for them to be in the docker group). 

They could build the containers all they please on their own machines, or download them from somewhere and then upload those to your cluster (without docker) where they can convert it to enroot.

**Comment by 3XX0** [comment]
Closing, the above use case can easily be addressed by having users install enroot on their own machines and upload the squashfs instead of the output of `docker save`. This is more efficient and enable other uses-cases (e.g. Pyxis squashfs launch)
