### ISSUE TITLE
RFE: parse credentials file, then swizzle docker URI

### ISSUE THREAD

**Issue by lukeyeager** [NVIDIA/enroot#8]
I have a feeling this will be the initial experience for most users when trying to import from a private registry:
```console
$ enroot import my-registry.com/foo/bar:v1.0
[ERROR] Invalid argument: my-registry.com/foo/bar:v1.0

$ # find out about the docker:// prefix

$ enroot import docker://my-registry.com/foo/bar:v1.0
[ERROR] URL https://registry-1.docker.io/v2/my-registry.com/foo/bar/manifests/v1.0 returned error code: 401 

$ # realize that URL doesn't look right
$ # find out about the '/' to '#' conversion

$ enroot import docker://my-registry.com#foo/bar:v1.0
[ERROR] URL https://my-registry.com/jwt/auth returned error code: 403 

$ # realize there's some sort of permissions error going on
$ # find out about the credentials file

$ echo "machine my-registry.com login $USER password $ACCESS_TOKEN" >>~/.config/enroot/.credentials
-bash: /home/lyeager/.config/enroot/credentials: No such file or directory
$ mkdir -p ~/.config/enroot/
$ echo "machine my-registry.com login $USER password $ACCESS_TOKEN" >>~/.config/enroot/.credentials
$ enroot import docker://my-registry.com#foo/bar:v1.0

$ # still didn't work ...
$ # on a whim, try adding the user explicitly

$ enroot import docker://lyeager@my-registry.com#foo/bar:v1.0

$ # OMG it works!
```
I have a proposal to help with some of that pain.

What if we parse the `.credentials` file before attempting to use curl. We keep a list of (machine,login) pairs. Then, we parse the URI given on the command line. If the registry is null, then the user may have forgotten to swap the "/" for a "#". Check to see if the first part of the image matches any hostname in the credentials file. If so, swap the next "/" for a "#". Also, add the "USER@" prefix to the URI if it is not present, since we can read the user from the credentials file.

**Comment by 3XX0** [comment]
It was not implemented this way mainly because of NGC, now that they fixed their authentication endpoint, it might be doable.

**Comment by lukeyeager** [comment]
What is the "interactive login"?

**Comment by 3XX0** [comment]
Same as the above but without the credential file, it will prompt for the password:
`enroot import docker://lyeager@my-registry.com#foo/bar:v1.0`

**Comment by lukeyeager** [comment]
Personally, I have never used the interactive login.

**Comment by dhudsmith** [comment]
Speaking as someone in the "most users" group, this was exactly the experience that I went through.
