### ISSUE TITLE
Tini is not running as PID 1 and isn't registered as a child subreaper.

### ISSUE THREAD

**Issue by kkvtran** [NVIDIA/enroot#82]
I got the following messages when I tried to 
srun enroot start sample-container 
[WARN  tini (66921)] 
Zombie processes will not be re-parented to Tini, so zombie reaping won't work.
To fix the problem, use the -s option or set the environment variable TINI_SUBREAPER to register Tini as a child subreaper, or run Tini as PID 1.

Any ideas or pointers?  Thanks.

**Comment by 3XX0** [comment]
There is no PID namespace in Enroot so no need for Tini or any other init system for that matter. Reaping will work as usual with your host init system.
