### ISSUE TITLE
Error when loading a NVIDIA container

### ISSUE THREAD

**Issue by smichnowicz** [NVIDIA/enroot#87]
Dear Sir/Madam
I used enroot to pull a nvidia container
enroot import docker://nvcr.io#nvidia/tensorflow:21.04-tf1-py3
I can enter this container with a simple command, but when I add extra flags, like trying to mount a file system,
it breaks upon error. The text is at the end of the message.  Can you advise please?

/usr/local/bin/nvidia_entrypoint.sh: line 81: exec: --: invalid option

thanks
Simon

 enroot start nvidia --env DISPLAY  --mount /fs03:/fs03
                                                                                                                                                
================
== TensorFlow ==
================

NVIDIA Release 21.04-tf1 (build 22382986)
TensorFlow Version 1.15.5

Container image Copyright (c) 2021, NVIDIA CORPORATION.  All rights reserved.
Copyright 2017-2021 The TensorFlow Authors.  All rights reserved.

NVIDIA Deep Learning Profiler (dlprof) Copyright (c) 2021, NVIDIA CORPORATION.  All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION.  All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license
ERROR: Detected NVIDIA Tesla K80 GPU, which is not supported by this container
ERROR: No supported GPU(s) detected to run this container

NOTE: Legacy NVIDIA Driver detected.  Compatibility mode ENABLED.

NOTE: MOFED driver was detected, but nv_peer_mem driver was not detected.
      Multi-node communication performance may be reduced.

/usr/local/bin/nvidia_entrypoint.sh: line 81: exec: --: invalid option
exec: usage: exec [-cl] [-a name] [command [arguments ...]] [redirection ...]

**Comment by flx42** [comment]
Hello,

You need to pass enroot options before the container name, the arguments after the container name are used as the command to execute + its arguments
```console
$ enroot start --help
Usage: enroot start [options] [--] NAME|IMAGE [COMMAND] [ARG...]
```

So you want the following instead:
```
$ enroot start --env DISPLAY --mount /fs03:/fs03 nvidia
```

**Comment by smichnowicz** [comment]
THanks. That fixed the problem.
