### ISSUE TITLE
Read-only ENROOT_DATA_PATH possible?

### ISSUE THREAD

**Issue by dr-br** [NVIDIA/enroot#91]
The unpacking of sqsh files consumes time and disk space.
Is it possible to provide already unpacked root file systems in a write-only ENROOT_DATA_PATH?

Unfortunately the lockfile `.lock` would be located in these write protected directories. 

Thanks!
Samuel

**Comment by 3XX0** [comment]
It's not possible to have the rootfs in a read-only filesystem because hooks need to be able to write to it.
Nothing stops you from unpacking it once and starting multiple containers from it (that's what the lock is for, and by default containers mount the filesystem filesystem as readonly)

**Comment by dr-br** [comment]
Thanks for the clarification!
