### ISSUE TITLE
ssh localhost inside container not working

### ISSUE THREAD

**Issue by wmutschl** [NVIDIA/enroot#92]
## Error description
For a certain software I need to be able to use "ssh localhost" inside a container. To be more precise, the software which runs inside the container uses ssh to communicate parallel tasks inside the container. So, I am NOT asking about ssh'ing into the container from my local machine.

Is this possible with enroot in general, because I am not able to do so unfortunately.

I do have a minimal example with docker which works and with enroot it does not.

## Minimal example with docker
```bash
docker pull rastasheep/ubuntu-sshd:16.04
docker run -d --name test_sshd rastasheep/ubuntu-sshd:16.04
docker exec -it test_sshd bash
```
In the container I can then successfully run `ssh localhost` and it connects.

## Minimal example with enroot
```bash
enroot import docker://rastasheep/ubuntu-sshd:16.04
enroot create --name test_sshd rastasheep+ubuntu-sshd+16.04.sqsh
enroot start --root --rw test_sshd bash
```
When I run `ssh localhost` this tries to connect to my local machine and does not stay in the container.

**Comment by wmutschl** [comment]
By the way, the [rastasheep/ubuntu-sshd](https://hub.docker.com/r/rastasheep/ubuntu-sshd/) container is equivalent to the following Dockerfile (based on [Dockerize an SSH service](https://web.archive.org/web/20200307091028/https://docs.docker.com/engine/examples/running_ssh_service/)):
```
FROM ubuntu:16.04

# Make SSH available
RUN apt-get update && apt-get install -y openssh-server
RUN mkdir /var/run/sshd
RUN echo 'root:root' | chpasswd
RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# SSH login fix. Otherwise user is kicked off after login
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
```

Similarly, if I do:
```
docker build -t ubuntu_sshd .
docker run -d --name test_sshd ubuntu_sshd
docker exec -it test_sshd bash
```
I can use `ssh localhost` without error.

Now if I import this Dockerfile with enroot:
```
enroot import dockerd://test_sshd
enroot start --root --rw test_sshd
# Missing privilege separation directory: /var/run/sshd
```

**Comment by wmutschl** [comment]
Looking into `/var/log/auth.log` on my host machine I can see that:
```
Sep 17 11:32:14 simba sshd[712503]: Connection closed by authenticating user root ::1 port 46138 [preauth]
```
So indeed from the container it is trying to connect to my host machine.

**Comment by wmutschl** [comment]
Does the enroot container get a certain ip I can use instead of localhost?

**Comment by 3XX0** [comment]
These two examples are different:

```
docker build -t ubuntu_sshd .
docker run -d --name test_sshd ubuntu_sshd
docker exec -it test_sshd bash
```

```
enroot import dockerd://ubuntu_sshd
enroot create --name test_sshd ubuntu_sshd.sqsh 
enroot start --root --rw test_sshd bash
```

In the first one you're starting `sshd` through the implicit command of `docker run`, and then `docker exec` into it.
In the second case you're overriding the image command with `bash` and `sshd` is not started.

Enroot container doesn't get its own ip but you can start a sshd server inside the container on say a different port.
Also, depending on how openssh has been compiled it might not like being run as remapped root. so you want to run it as your normal user:
```
enroot import dockerd://ubuntu_sshd
enroot create --name test_sshd ubuntu_sshd.sqsh

# Optional if you want your home to be mounted and reuse your SSH keys from the host
export ENROOT_MOUNT_HOME=y 

enroot start test_sshd /usr/sbin/sshd -D -p 2222 &
enroot exec $! ssh -p 2222 localhost
```

**Comment by wmutschl** [comment]
Thank you for your input, this clarified some differences between docker and enroot for me! However, when I run your suggestion I get the following:
```
enroot start test_sshd /usr/sbin/sshd -D -p 2222 &
# Missing privilege separation directory: /var/run/sshd
# Job 1, 'enroot start test_sshd /usr/sbi…' has ended
```
What am I missing?

**Comment by 3XX0** [comment]
This usually means `sshd` is being run as "root", you might have `ENROOT_REMAP_ROOT=y` set by default in your enroot.conf.

You can disable it for this container specifically:
`ENROOT_REMAP_ROOT=n enroot start test_sshd /usr/sbin/sshd -D -p 2222 &`

Otherwise you can create the directory as a new mountpoint:
`enroot start -m tmpfs:/run/sshd:x-create=dir,mode=0600 test_sshd /usr/sbin/sshd -D -p 2222 &`

But again if your openssh is not compiled to support remapped root you will see failures when authenticating similar to:

`permanently_set_uid: was able to restore old [e]gid [preauth]`
