### ISSUE TITLE
coreutils >8.32 will break enroot import

### ISSUE THREAD

**Issue by dr-br** [NVIDIA/enroot#98]
Dear developers,
as soon as coreutils >8.32 is installed, `enroot import` will terminate after `[INFO] Extracting image content...` and no sqsh-file is generated. 
```
...
[INFO] Extracting image content...
[{WIFEXITED(s) && WEXITSTATUS(s) == 1}], 0, NULL) = 57295
rt_sigaction(SIGINT, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fa571ed4da0}, {sa_handler=0x558892a3cae0, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fa571ed4da0}, 8) = 0
ioctl(2, TIOCGWINSZ, {ws_row=50, ws_col=105, ws_xpixel=0, ws_ypixel=0}) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=57295, si_uid=1000, si_status=1, si_utime=0, si_stime=0} ---
wait4(-1, 0x7fff458e7c90, WNOHANG, NULL) = -1 ECHILD (Keine Kind-Prozesse)
rt_sigreturn({mask=[]})                 = 0
rt_sigprocmask(SIG_BLOCK, [CHLD], [], 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
exit_group(1)                           = ?
+++ exited with 1 +++
```
Coreutils 9.0 will be / is already available e.g. on Arch Linux.

Possibly, the new CoW could be responsible for this problem. (edit: No, using ext4)

Other enroot commands are not affected AFAIK.

**Comment by 3XX0** [comment]
Looks like it has been fixed: https://github.com/coreutils/coreutils/commit/e8b56ebd536e82b15542a00c888109471936bfda
Although since it shipped already I guess we can make this non fatal in the enroot case.
